### ISSUE TITLE
List with extension call causes NPE in BaseParser

### ISSUE THREAD

**Issue by kepuss** [jamesagnew/hapi-fhir#1029]
Hi, 
We are upgrading fhir server from 2.3 -> 3.4.0
Between versions 3.0.0 and 3.1.0 there where change in BaseParser which throws NPE.

This is the part that causes theElements set to be null
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java#L1070
```
Set<String> encodeElements = myEncodeElements;
if (encodeElements != null && encodeElements.isEmpty() == false) {
	if (isEncodeElementsAppliesToChildResourcesOnly() && !mySubResource) {
		encodeElements = null;
	}
}
```

And this is the place where NPE is triggered:
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/BaseParser.java#L1124
```
boolean retVal = theElements.contains(currentPath);
```
This is how we call server:
```
/fhir/baseDstu3/List?subject=12&_elements=identifier,status,date,extension
```
Stacktrace:
```
2018-07-17 13:55:32.495 [qtp1631959070-22] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:154] Failure during REST processing: java.lang.NullPointerException
java.lang.NullPointerException: null
	at ca.uhn.fhir.parser.BaseParser$CompositeChildElement.checkIfPathMatchesForEncoding(BaseParser.java:1124)
	at ca.uhn.fhir.parser.BaseParser$CompositeChildElement.checkIfParentShouldBeEncodedAndBuildPath(BaseParser.java:1077)
	at ca.uhn.fhir.parser.BaseParser$CompositeChildElement.shouldBeEncoded(BaseParser.java:1159)
	at ca.uhn.fhir.parser.BaseParser$1$1.hasNext(BaseParser.java:115)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:334)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:548)
	at ca.uhn.fhir.parser.JsonParser.encodeChildElementToStreamWriter(JsonParser.java:268)
	at ca.uhn.fhir.parser.JsonParser.access$700(JsonParser.java:58)
	at ca.uhn.fhir.parser.JsonParser$HeldExtension.writeUndeclaredExtension(JsonParser.java:1452)
	at ca.uhn.fhir.parser.JsonParser$HeldExtension.write(JsonParser.java:1361)
	at ca.uhn.fhir.parser.JsonParser.writeExtensionsAsDirectChild(JsonParser.java:1267)
	at ca.uhn.fhir.parser.JsonParser.extractAndWriteExtensionsAsDirectChild(JsonParser.java:742)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:341)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:548)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:702)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:598)
	at ca.uhn.fhir.parser.JsonParser.encodeChildElementToStreamWriter(JsonParser.java:314)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:459)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:548)
	at ca.uhn.fhir.parser.JsonParser.encodeChildElementToStreamWriter(JsonParser.java:268)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:455)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:548)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:702)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:598)
	at ca.uhn.fhir.parser.JsonParser.doEncodeResourceToJsonLikeWriter(JsonParser.java:150)
	at ca.uhn.fhir.parser.JsonParser.doEncodeResourceToWriter(JsonParser.java:157)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:318)
	at ca.uhn.fhir.rest.server.RestfulServerUtils.streamResponseAsResource(RestfulServerUtils.java:714)
	at ca.uhn.fhir.rest.server.RestfulResponse.streamResponseAsResource(RestfulResponse.java:88)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:401)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:921)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:335)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:247)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
[WARNING] /fhir/baseDstu3/List
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:874)
	at ca.uhn.fhir.rest.server.servlet.ServletRestfulResponse.getResponseWriter(ServletRestfulResponse.java:72)
	at ca.uhn.fhir.rest.server.RestfulServerUtils.streamResponseAsResource(RestfulServerUtils.java:706)
	at ca.uhn.fhir.rest.server.RestfulResponse.streamResponseAsResource(RestfulResponse.java:88)
	at ca.uhn.fhir.rest.server.interceptor.ExceptionHandlingInterceptor.handleException(ExceptionHandlingInterceptor.java:97)
	at ca.uhn.fhir.rest.server.interceptor.ExceptionHandlingInterceptor.handleException(ExceptionHandlingInterceptor.java:58)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:994)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:335)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1494)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:247)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
```

Could you tell me if this is a bug. or there was some logic change between 3.0.0 and 3.1.0 versions?

**Comment by jamesagnew** [comment]
Hi @kepuss ,

Can you please provide a code sample showing how to trigger this issue?

**Comment by kepuss** [comment]
Hi @jamesagnew 
sorry that it took so long. But I managed to create seperate project where I recreated the problem.
https://github.com/kepuss/hapi-tests

**Comment by kepuss** [comment]
Hi @jamesagnew 
Any update? Can I help somehow?
