### ISSUE TITLE
Failed resolution of: Lorg/apache/http/impl/conn/PoolingHttpClientConnectionManager;

### ISSUE THREAD

**Issue by vicksWalkiria** [jamesagnew/hapi-fhir#1045]
Hello all. I'm trying to connect to the test server to upload a QuestionnaireResponse object from an Android client. This is my code:

```
     FhirContext ctx = FhirContext.forDstu2();
        String serverBase = "http://hapi.fhir.org/baseDstu2";


        IGenericClient client = ctx.newRestfulGenericClient(serverBase);
        MethodOutcome outcome = client.create()
                .resource(STRING_TO_SEND)
                .prettyPrint()
                .encodedJson()
                .execute();
```

But I'm getting this error:

>  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/conn/PoolingHttpClientConnectionManager;
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getNativeHttpClient(ApacheRestfulClientFactory.java:76)
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getHttpClient(ApacheRestfulClientFactory.java:132)
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getHttpClient(ApacheRestfulClientFactory.java:51)
        at ca.uhn.fhir.rest.client.RestfulClientFactory.newGenericClient(RestfulClientFactory.java:189)
        at ca.uhn.fhir.context.FhirContext.newRestfulGenericClient(FhirContext.java:479)
        at com.salumedia.cancerlens.Views.MainActivity.onCreate(MainActivity.java:179)
        at android.app.Activity.performCreate(Activity.java:6284)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2518)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2652)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1487)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5726)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.conn.PoolingHttpClientConnectionManager" on path: DexPathList[[zip file "/data/app/com.salumedia.cancerlens-2/base.apk"],nativeLibraryDirectories=[/data/app/com.salumedia.cancerlens-2/lib/arm, /data/app/com.salumedia.cancerlens-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getNativeHttpClient(ApacheRestfulClientFactory.java:76) 
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getHttpClient(ApacheRestfulClientFactory.java:132) 
        at ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory.getHttpClient(ApacheRestfulClientFactory.java:51) 
        at ca.uhn.fhir.rest.client.RestfulClientFactory.newGenericClient(RestfulClientFactory.java:189) 
        at ca.uhn.fhir.context.FhirContext.newRestfulGenericClient(FhirContext.java:479) 
        at com.salumedia.cancerlens.Views.MainActivity.onCreate(MainActivity.java:179) 
        at android.app.Activity.performCreate(Activity.java:6284) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2518) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2652) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1487) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5726) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749) 
    	Suppressed: java.lang.ClassNotFoundException: org.apache.http.impl.conn.PoolingHttpClientConnectionManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 19 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

I'm come to ApacheRestfulClientFactory class and I've found this:
![imagen](https://user-images.githubusercontent.com/16098931/43385266-8c4f958a-93e0-11e8-93ee-69a8fe9bfd0a.png)

PoolingHttpClientConnectionManager  appears in red and shows 'cannot resolve symbol' message.

How can I fix this?

Thanks in advance.

**Comment by jamesagnew** [comment]
Hi Victor,

For Android you need to use the hapi-fhir-android library, which relies on
OkHttp instead of Apache HttpClient.

See the Android Integration Test for a sample of how to set this up:
https://github.com/hapifhir/hapi-fhir-android-integration-test

Cheers,
James

**Comment by Imane81** [comment]
Hi,
I had the same problem. Did you succeed in solving it?
