### ISSUE TITLE
Proxy Authentication Required while credentials are given

### ISSUE THREAD

**Issue by mharthoorn** [jamesagnew/hapi-fhir#107]
Error found during connectathon Helsinki by one of the participants.

Error message: 
```java
Exception in thread "main" ca.uhn.fhir.rest.server.exceptions.UnclassifiedServerFailureException: HTTP 407 Proxy Authentication Required 
            at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:263) 
            at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:235) 
            at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:130) 
            at ca.uhn.fhir.rest.client.GenericClient.read(GenericClient.java:250) 
            at fi.kela.fhir.FhirClient.main(FhirClient.java:53) 
```  
Source code: 
```java
final String authUser = "username"; 
final String authPassword = "password"; 
CredentialsProvider credsProvider = new BasicCredentialsProvider(); 
credsProvider.setCredentials(new AuthScope("10.10.10.10", 8080), 
            new UsernamePasswordCredentials(authUser, authPassword)); 
HttpHost myProxy = new HttpHost("10.10.10.10", 8080); 
HttpClientBuilder clientBuilder = HttpClientBuilder.create(); 
  
clientBuilder.setProxy(myProxy) 
.setDefaultCredentialsProvider(credsProvider) 
            .disableCookieManagement(); 
                         
CloseableHttpClient httpClient = clientBuilder.build(); 
                         
FhirContext ctx = new FhirContext(); 
String serverBase = "http://spark.furore.com/fhir/"; 
ctx.getRestfulClientFactory().setHttpClient(httpClient); 
IGenericClient client = ctx.newRestfulGenericClient(serverBase); 
  
IdDt id = new IdDt("Patient", "123"); 
client.read(Patient.class, id); 
```

**Comment by jamesagnew** [comment]
Hi Martijn,
I *think* this is just a case of a single missing configuration item on the Apache HttpClient, instructing it to actually authenticate with the proxy. I don't know why you need to do that when you've already provided credentials, but HttpClient is a bit overengineered frankly. :)
```
      HttpClientBuilder clientBuilder = HttpClientBuilder.create(); 
      clientBuilder
         .setProxy(myProxy)
         .setProxyAuthenticationStrategy(new ProxyAuthenticationStrategy())
         .setDefaultCredentialsProvider(credsProvider) 
         .disableCookieManagement(); 
      CloseableHttpClient httpClient = clientBuilder.build();
```

**Comment by jamesagnew** [comment]
Documentation has been updated to make this clearer. Closing issue.

Thanks for reporting!
