### ISSUE TITLE
Error parsing procedure inside Bundle

### ISSUE THREAD

**Issue by dMitin** [jamesagnew/hapi-fhir#1072]
**Describe the bug**
Exception when trying to parse Procedure resource inside Bundle.

**To Reproduce**
1. Parse FHIR
```json
{
  "resourceType":"Bundle",
  "type":"transaction",
  "total":1,
  "entry":[
    {
      "resourceType": "Procedure",
      "id": "example",
      "text": {
        "status": "generated",
        "div": "<div>Routine Appendectomy</div>"
      },
      "subject": {
        "reference": "Patient/example"
      },
      "status": "completed",
      "code": {
        "coding": [
          {
            "system": "http://snomed.info/sct",
            "code": "80146002",
            "display": "Appendectomy (Procedure)"
          }
        ],
        "text": "Appendectomy"
      },
      "reasonCodeableConcept": {
        "text": "Generalized abdominal pain 24 hours. Localized in RIF with rebound and guarding"
      },
      "performer": [
        {
          "actor": {
            "reference": "Practitioner/example",
            "display": "Dr Cecil Surgeon"
          }
        }
      ],
      "performedDateTime": "2013-04-05",
      "followUp": [
        {
          "text": "ROS 5 days  - 2013-04-10"
        }
      ],
      "notes": [
        {
          "text": "Routine Appendectomy. Appendix was inflamed and in retro-caecal position"
        }
      ]
    }
  ]
}
```
When you execute 
```java
FhirContext ourCtx = FhirContext.forDstu2();
IParser parser = ourCtx.newJsonParser();
parser.setParserErrorHandler(new StrictErrorHandler());
parser.parseResource(object.toString());
``` 
I got exception
```
ca.uhn.fhir.parser.DataFormatException: Unknown element 'text' found during parse

	at ca.uhn.fhir.parser.StrictErrorHandler.unknownElement(StrictErrorHandler.java:78)
	at ca.uhn.fhir.parser.ParserState$ElementCompositeState.enteringNewElement(ParserState.java:530)
	at ca.uhn.fhir.parser.ParserState.enteringNewElement(ParserState.java:91)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1008)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:937)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1020)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1001)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:937)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:183)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:165)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:654)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:703)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:713)
```
**Expected behavior**
Successfully parsing.

**Environment (please complete the following information):**
 - HAPI FHIR Version 3.3.0 (the same result in 3.4.0)
 - OS: Windows
 - Browser no Browser

**Additional context**
This Procedure resource was used from official site https://www.hl7.org/fhir/DSTU2/procedure-example.json.html . If we parse this resource itself, all works fine. If we put this resource into Bundle (as in example) problem arises.
If you have problems with reproducing this error, i can provide mvn project.

**Comment by dMitin** [comment]
Working example please look here
https://github.com/dMitin/fhir-procedure-parse

**Comment by dMitin** [comment]
The problen was in structure of bundle.
Right structure is something like that
```json
"fullUrl": "Procedire/1",
      "resource" : { ...}
```
