### ISSUE TITLE
Error upgrading database from 3.4 to 3.5

### ISSUE THREAD

**Issue by seanmcilvenna** [jamesagnew/hapi-fhir#1106]
When executing: java -jar hapi-fhir-cli.jar migrate-database -d MYSQL_5_7 -f V3_4_0 -t V3_5_0 -u "jdbc:mysql://localhost:3306/hapi_localhost?useSSL=false" -n XXX -p XXX

I am receiving the following error:

2018-10-29 10:48:25 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT * FROM HFJ_SPIDX_COORDS WHERE HASH_IDENTITY IS NULL]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'HASH_IDENTITY' in 'where clause'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:446)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456)
        at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:484)
        at ca.uhn.fhir.jpa.migrate.taskdef.CalculateHashesTask.lambda$execute$0(CalculateHashesTask.java:61)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at ca.uhn.fhir.jpa.migrate.taskdef.CalculateHashesTask.execute(CalculateHashesTask.java:56)
        at ca.uhn.fhir.jpa.migrate.Migrator.migrate(Migrator.java:82)
        at ca.uhn.fhir.cli.BaseMigrateDatabaseCommand.run(BaseMigrateDatabaseCommand.java:108)
        at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:243)
        at ca.uhn.fhir.cli.App.main(App.java:43)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'HASH_IDENTITY' in 'where clause'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
        at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:433)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
        ... 10 common frames omitted
2018-10-29 10:48:25 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...

**Comment by seanmcilvenna** [comment]
3.5 is old now. Closing ticket.
