### ISSUE TITLE
java.lang.UnsupportedOperationException thrown during validation since update to 3.7.0

### ISSUE THREAD

**Issue by rprobinson** [jamesagnew/hapi-fhir#1225]
## Background:
I have integrated HAPI FHIR Validation library into the NHS Digital Validation tooling (STU3). I have extended the tool using the iValidationSupport to accept the NHS profiles (StructureDefinitions, ValueSets, CodeSystems...). Suppliers have been using this for some time and it has been executed running v3.4.0 and v3.6.0. Under these versions no exceptions are reported.
I reported an issue whereby HAPI FHIR Validator entered an infinite loop in December (https://github.com/jamesagnew/hapi-fhir/issues/1149) which was fixed and included in v3.7.0, which I am now testing.
- OS: Linux Ubuntu 16.04

## Observation of issue:
Now when I validate this message ([BundleMessage.txt](https://github.com/jamesagnew/hapi-fhir/files/2930644/BundleMessage.txt)) using v3.7.0, it throws 2 java.lang.UnsupportedOperationException

The stdout shows:

```[main] INFO com.helger.jaxb.JAXBContextCache - Creating JAXB context for package org.oclc.purl.dsdl.svrl using ClassLoader sun.misc.Launcher$AppClassLoader@14dad5dc
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-resources.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-types.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-others.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/extension/extension-definitions.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/valuesets.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/v2-tables.xml
[main] INFO org.hl7.fhir.dstu3.hapi.validation.DefaultProfileValidationSupport - Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/v3-codesystems.xml
java.lang.UnsupportedOperationException
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator$WorkerContextWrapper.expandVS(FhirInstanceValidator.java:535)
	at org.hl7.fhir.r4.elementmodel.Element.getAsICoding(Element.java:775)
	at org.hl7.fhir.r4.model.Base.castToCoding(Base.java:486)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.opMemberOf(FHIRPathEngine.java:1735)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1333)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1119)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1100)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1118)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:503)
	at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluateToBoolean(FHIRPathEngine.java:559)
	at org.hl7.fhir.r4.validation.InstanceValidator.evaluateSlicingExpression(InstanceValidator.java:2571)
	at org.hl7.fhir.r4.validation.InstanceValidator.sliceMatches(InstanceValidator.java:2563)
	at org.hl7.fhir.r4.validation.InstanceValidator.matchSlice(InstanceValidator.java:3801)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3505)
	at org.hl7.fhir.r4.validation.InstanceValidator.start(InstanceValidator.java:2681)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateResource(InstanceValidator.java:4020)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateContains(InstanceValidator.java:3415)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3703)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3708)
	at org.hl7.fhir.r4.validation.InstanceValidator.start(InstanceValidator.java:2681)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateResource(InstanceValidator.java:4020)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateContains(InstanceValidator.java:3415)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3703)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3708)
	at org.hl7.fhir.r4.validation.InstanceValidator.start(InstanceValidator.java:2681)
	at org.hl7.fhir.r4.validation.InstanceValidator.validateResource(InstanceValidator.java:4020)
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:713)
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:639)
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:618)
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator.validate(FhirInstanceValidator.java:326)
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator.validate(FhirInstanceValidator.java:396)
	at org.hl7.fhir.dstu3.hapi.validation.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:20)
	at org.hl7.fhir.dstu3.hapi.validation.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:43)
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:54)
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:213)
```

When I follow the error link to FhirInstanceValidator.java:535 this is the code:

```@Override
public ValueSetExpander.ValueSetExpansionOutcome expandVS(org.hl7.fhir.r4.model.ElementDefinition.ElementDefinitionBindingComponent binding, boolean cacheOk, boolean heiarchical) {
			throw new UnsupportedOperationException();
}
```

...which looks like it's an auto-generated method from the IDE. Is there some code missing here? Or am I accessing this code when I ought not to be?

In support here is a screenshot of the debug variable "binding" which is passed into the expandVS method: 
![screenshot at 2019-03-05 10 37 36](https://user-images.githubusercontent.com/13271321/53801274-a4f7d500-3f36-11e9-872a-f5db78010095.png)
It seems to be referencing the ValueSet: "http://hl7.org/fhir/ValueSet/name-use"

Any help would be gratefully received.
Thank you 
Richard Robinson

**Comment by jamesagnew** [comment]
Hmm, weirdly if I validate your bundle against our public server it seems to hang indefinitely.

Just to confirm, is this using the validator as a standalone component (i.e. not built-into the HAPI FHIR JPA server or anything like that?)

**Comment by KevinMayfield** [comment]
I’m getting the same issue.

It’s caused when the validator starts up and tries to load in the v3 CodeSystems / ValueSets

19-03-06 07:00:14.691  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-resources.xml
2019-03-06 07:00:15.461  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-types.xml
2019-03-06 07:00:15.525  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/profile/profiles-others.xml
2019-03-06 07:00:15.727  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading structure definitions from classpath: /org/hl7/fhir/dstu3/model/extension/extension-definitions.xml
2019-03-06 07:00:23.708  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/valuesets.xml
2019-03-06 07:00:24.168  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/v2-tables.xml
2019-03-06 07:00:24.864  INFO 41407 --- [nio-8186-exec-2] .f.d.h.v.DefaultProfileValidationSupport : Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/dstu3/model/valueset/v3-codesystems.xml

I’m checking configuration of my validator to see if it changed from 3.6 to 3.7

**Comment by KevinMayfield** [comment]
It's a non fatal error when I include this in my pom, it still occurs but validate returns a result

     <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-validation</artifactId>
            <version>${hapi-fhir-version}</version>
        </dependency>

Code like this should reproduce 

     ValidationSupportChain validationSupportChain = new ValidationSupportChain();

        validationSupportChain.addValidationSupport(new DefaultProfileValidationSupport());

**Comment by rprobinson** [comment]
> Hmm, weirdly if I validate your bundle against our public server it seems to hang indefinitely.
> 
> Just to confirm, is this using the validator as a standalone component (i.e. not built-into the HAPI FHIR JPA server or anything like that?)

I am using the hapi-fhir-validation-3.7.0.jar and calling it from within our tool. I had upgraded from 3.6.0 as a result of the validation entering such a state of hanging with 100% CPU utilisation. On my installation it fixes that issue and successfully validates but does also throw the exception as outlined above. Can you confirm that the fix from https://github.com/jamesagnew/hapi-fhir/issues/1149 has been integrated into 3.7.0? I looked in the release notes but couldnt see it - I had assumed it had.
