### ISSUE TITLE
Unable to start Hapi fhir 3.7.0 in TomEE 7

### ISSUE THREAD

**Issue by thangaraj14** [jamesagnew/hapi-fhir#1260]
Unable to start the server TomEE 7 which has JDK8 after upgrading 3.5.0 to 3.7.0. 
We are not using any of this libs also : http://hapifhir.io/changes-report.html#_toc_release_370__2019-02-06 .

Logs : 
#+00#ERROR#org.apache.catalina.core.ContainerBase##anonymous#localhost-startStop-1#na#wb3da9a4f#healthengagement#web##na#na#na#na#ContainerBase.addChild: start:  org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/abc]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module abc: null
	at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2305)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1188)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 common frames omitted
Caused by: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module abc: null
	at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:886)
	at org.apache.openejb.config.DeploymentLoader.load(DeploymentLoader.java:233)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2303)
	... 16 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:1169)
	at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:147)
	at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:160)
	at org.apache.openejb.config.FinderFactory$OpenEJBAnnotationFinder.<init>(FinderFactory.java:546)
	at org.apache.openejb.config.FinderFactory.newFinder(FinderFactory.java:267)
	at org.apache.openejb.config.FinderFactory.create(FinderFactory.java:80)
	at org.apache.openejb.config.FinderFactory.createFinder(FinderFactory.java:69)
	at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:878)
	... 18 common frames omitted
|
2019 03 27 08:01:50#+00#ERROR#org.apache.catalina.startup.HostConfig##anonymous#localhost-startStop-1#na#wb3da9a4f#healthengagement#web##na#na#na#na#Error deploying web application archive [abc.war] java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/abc]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:758)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
|

**Comment by jamesagnew** [comment]
What is "abc" that appears in the errors? Are there other errors? Does the
hapi-fhir-jpaserver-starter project work for you?

sent from my phone.

**Comment by thangaraj14** [comment]
"abc" is supposed to be a project name. I dont have hapi-fhir-jpaserver-starter jar. I have hapi-fhir-base,hapi-fhir-server and hapi-fhir-structures-r4 in my project.
