### ISSUE TITLE
Property.setProperty(String name, Base value) fails w/ NullPointerException when value is null

### ISSUE THREAD

**Issue by keithboone** [jamesagnew/hapi-fhir#1276]
**Describe the bug**
Property.setProperty(String name, Base value) fails w/ ClassCastException when value is null

**To Reproduce**
Using any resource, call r.setProperty("<name>", null);

**Expected behavior**
The property will be set to null.

**Screenshots**
java.lang.NullPointerException
	at org.hl7.fhir.instance.model.Base.castToDateTime(Base.java:288)
	at org.hl7.fhir.instance.model.Conformance.setProperty(Conformance.java:7530)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.6.0
 - OS: Windows 10
 - Browser N/A

**Additional context**
castTo* methods should return null when passed a null value.

**Comment by keithboone** [comment]
the problem is in missing bolded code shown here:

	public InstantType castToInstant(Base b) throws FHIRException {
                **if (b == null) { 
                        return null;
                } else** 
		if (b instanceof InstantType)
			return (InstantType) b;
		else
			throw new FHIRException("Unable to convert a "+b.getClass().getName()+" to a Instant");
	}
