### ISSUE TITLE
Validation of r4 schema json displays error message but validation is successful

### ISSUE THREAD

**Issue by soroushatarod** [jamesagnew/hapi-fhir#1285]
**Describe the bug**
Validation of a schema in JSON is successful but there are error messages being displayed. for example:

- ```Bad assert: XPath syntax error. Unclosed parenthesis. Suggestion: add ')'.
      f:type/@value=('choice','open-choice','decimal','integer','date','dateTime','time','string','quantity',') or not(f:answerOption or f:answerValueSet)```
- [fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Unmatched quote in expression)

**Schema**

```
{
	"resourceType": "Questionnaire",
	"title": "Cancer Quality Forum Questionnaire 2012",
	"status": "draft",
	"item": [
		{
			"linkId": "1.1",
			"text": "Do you currently have any symptoms?",
			"type": "boolean",
			"item": [
				{
					"linkId": "1.2",
					"prefix": "1.3",
					"type": "group",
					"enableWhen": [
						{
							"question": "1.1",
							"operator": "=",
							"answerBoolean": true
						}
					],
					"item": [
						{
							"linkId": "1.3",
							"text": "Thank you for your answer, please explain more",
							"type": "string"
						}
					]
				}
			]
		}
	]
}
```

**To Reproduce**
```
FhirContext r4 = FhirContext.forR4();
	
		
		String schema = "String msgString = \"<Patient xmlns=\\\"http://hl7.org/fhir\\\">\"\n" + 
				"  + \"<text><status value=\\\"generated\\\" /><div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">John Cardinal</div></text>\"\n" + 
				"  + \"<identifier><system value=\\\"http://orionhealth.com/mrn\\\" /><value value=\\\"PRP1660\\\" /></identifier>\"\n" + 
				"  + \"<name><use value=\\\"official\\\" /><family value=\\\"Cardinal\\\" /><given value=\\\"John\\\" /></name>\"\n" + 
				"  + \"<gender><coding><system value=\\\"http://hl7.org/fhir/v3/AdministrativeGender\\\" /><code value=\\\"M\\\" /></coding></gender>\"\n" + 
				"  + \"<address><use value=\\\"home\\\" /><line value=\\\"2222 Home Street\\\" /></address><active value=\\\"true\\\" />\"\n" + 
				"  + \"</Patient>\";";
		
        FhirValidator customValidator = r4.newValidator();
        customValidator.setValidateAgainstStandardSchema(true);
        customValidator.setValidateAgainstStandardSchematron(true);
        
       
		ValidationResult result = customValidator.validateWithResult(schema);
		
		if (result.isSuccessful()) {
			System.out.println("SUCCESS");
		} else {
			System.out.println("FAIL");
		}
		
		return schema;
```

**Expected behavior**
Should not display any error messages as the schema is valid.

**Screenshots**
```2019-04-23 18:14:27.144  INFO 51369 --- [nio-8080-exec-1] ca.uhn.fhir.util.VersionUtil             : HAPI FHIR version 3.7.0 - Rev f2560071c8
2019-04-23 18:14:27.145  INFO 51369 --- [nio-8080-exec-1] ca.uhn.fhir.context.FhirContext          : Creating new FHIR context for FHIR version [R4]
2019-04-23 18:14:27.590  INFO 51369 --- [nio-8080-exec-1] ca.uhn.fhir.util.XmlUtil                 : FHIR XML procesing will use StAX implementation 'Java Runtime Environment' version '1.8.0_201'
Bad assert: XPath syntax error. Unclosed parenthesis. Suggestion: add ')'.
      f:type/@value=('choice','open-choice','decimal','integer','date','dateTime','time','string','quantity',') or not(f:answerOption or f:answerValueSet)
2019-04-23 18:14:28.915 ERROR 51369 --- [nio-8080-exec-1] c.h.x.t.LoggingTransformErrorListener    : [fatal_error] Transformation fatal error (net.sf.saxon.trans.XPathException: Unmatched quote in expression)
2019-04-23 18:14:28.929 ERROR 51369 --- [nio-8080-exec-1] c.h.xml.transform.XMLTransformerFactory  : Failed to parse javax.xml.transform.dom.DOMSource@7f3782e2

javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:152) ~[Saxon-HE-9.9.0-1.jar:na]
	at com.helger.xml.transform.XMLTransformerFactory.newTemplates(XMLTransformerFactory.java:300) ~[ph-xml-9.2.0.jar:9.2.0]
	at com.helger.schematron.xslt.SchematronProviderXSLTFromSCH.<init>(SchematronProviderXSLTFromSCH.java:223) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.xslt.SchematronResourceSCHCache.createSchematronXSLTProvider(SchematronResourceSCHCache.java:69) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.xslt.SchematronResourceSCHCache.getSchematronXSLTProvider(SchematronResourceSCHCache.java:145) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.xslt.SchematronResourceSCH.getXSLTProvider(SchematronResourceSCH.java:92) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.xslt.AbstractSchematronXSLTBasedResource.isValidSchematron(AbstractSchematronXSLTBasedResource.java:194) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.AbstractSchematronResource.applySchematronValidationToSVRL(AbstractSchematronResource.java:262) [ph-schematron-5.0.8.jar:5.0.8]
	at com.helger.schematron.SchematronHelper.applySchematron(SchematronHelper.java:132) [ph-schematron-5.0.8.jar:5.0.8]
	at ca.uhn.fhir.validation.schematron.SchematronBaseValidator.validateResource(SchematronBaseValidator.java:85) [hapi-fhir-base-3.7.0.jar:na]
	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:235) [hapi-fhir-base-3.7.0.jar:na]
	at com.example.demo.AlienResource.hello(AlienResource.java:266) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.17.jar:9.0.17]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:781) ~[Saxon-HE-9.9.0-1.jar:na]
	at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:149) ~[Saxon-HE-9.9.0-1.jar:na]
	... 65 common frames omitted
Caused by: net.sf.saxon.trans.XPathException: Errors were reported during stylesheet compilation
	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:260) ~[Saxon-HE-9.9.0-1.jar:na]
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:107) ~[Saxon-HE-9.9.0-1.jar:na]
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:778) ~[Saxon-HE-9.9.0-1.jar:na]
	... 66 common frames omitted

2019-04-23 18:14:28.929  WARN 51369 --- [nio-8080-exec-1] c.h.s.xslt.SchematronResourceSCHCache    : The Schematron resource 'jar:file:/Users/soroushatarod/.m2/repository/ca/uhn/hapi/fhir/hapi-fhir-validation-resources-r4/3.7.0/hapi-fhir-validation-resources-r4-3.7.0.jar!/org/hl7/fhir/r4/model/schema/questionnaire.sch' is invalid!
SUCCESS
2019-04-23 18:18:51.676  INFO 51369 --- [n(20)-127.0.0.1] inMXBeanRegistrar$SpringApplicationAdmin : Application shutdown requested.
2019-04-23 18:18:51.679  INFO 51369 --- [n(20)-127.0.0.1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
SUCCESS
```

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0
 - OS: MAC OS
 - Java
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode

**Additional context**

**Comment by skonchada** [comment]
@soroushatarod - I am facing the same issue, was this issue resolved? I am on HAPI FHIR 3.8
