### ISSUE TITLE
DataFormatException after converting MedicationAdministration with dosage.rateQuantity using VersionConvertor_30_40

### ISSUE THREAD

**Issue by aschnab** [jamesagnew/hapi-fhir#1295]
**Describe the bug**
When I try to convert a MedicationAdministration containing the dosage.rateQuantity field from R4 to DSTU3 using VersionConvertor_30_40.convertMedicationAdministration, and to output the resulting DSTU3 object, I get a ca.uhn.fhir.parser.DataFormatException.
It seems to me that the result of the conversion (the DSTU3 MedicationAdministration) is not entirely valid because its dosage.rate is of the class Quantity, but not of the (sub-)class SimpleQuantity. On trying to output this object, the parser complains about this problem:
```
Exception in thread "main" ca.uhn.fhir.parser.DataFormatException: rate has type org.hl7.fhir.dstu3.model.Quantity but this is not a valid type for this element - Expected one of: [class org.hl7.fhir.dstu3.model.Ratio, class org.hl7.fhir.dstu3.model.SimpleQuantity]
	at ca.uhn.fhir.parser.BaseParser.throwExceptionForUnknownChildType(BaseParser.java:961)
	at ca.uhn.fhir.parser.BaseParser.getChildNameAndDef(BaseParser.java:377)
	at ca.uhn.fhir.parser.XmlParser.encodeCompositeElementToStreamWriter(XmlParser.java:387)
	at ca.uhn.fhir.parser.XmlParser.encodeChildElementToStreamWriter(XmlParser.java:274)
	at ca.uhn.fhir.parser.XmlParser.encodeCompositeElementToStreamWriter(XmlParser.java:409)
	at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:497)
	at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:470)
	at ca.uhn.fhir.parser.XmlParser.doEncodeResourceToWriter(XmlParser.java:112)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:315)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:299)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:288)
	(...)
```

**To Reproduce**
The following Java code using HAPI FHIR 3.7.0 produces the exception cited above:
```
	private static MedicationAdministration getMedicationAdministration() {
		MedicationAdministration medicationAdministration = new MedicationAdministration();
		medicationAdministration.setId("example");
		medicationAdministration.setStatus("in-progress");
		medicationAdministration.setMedication(new Reference("Medication/123"));
		medicationAdministration.setSubject(new Reference("Patient/234"));
		medicationAdministration.setEffective(new DateTimeType("2019-05-02T12:00:00+02:00"));
		MedicationAdministrationDosageComponent dosageComponent = new MedicationAdministrationDosageComponent();
		SimpleQuantity rate = new SimpleQuantity();
		rate.setValue(20);
		dosageComponent.setRate(rate);
		medicationAdministration.setDosage(dosageComponent);
		return medicationAdministration;
	}

	public static void main(String[] args) throws Exception {
		MedicationAdministration medAdmin = getMedicationAdministration();
		org.hl7.fhir.dstu3.model.MedicationAdministration dstu3MedAdmin = VersionConvertor_30_40.convertMedicationAdministration(medAdmin);
		FhirContext ctx = FhirContext.forDstu3();
		IParser xmlParser = ctx.newXmlParser();
		xmlParser.encodeResourceToString(dstu3MedAdmin);
	}
```

**Expected behavior**
The result of calling VersionConvertor_30_40.convertMedicationAdministration should be a "clean" DSTU3 MedicationAdministration object that can be handled by other functionality of HAPI (such the parsers' string encoding methods) without any problems.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0
 - OS: [e.g. iOS]: Fedora 29
 - Browser [e.g. chrome, safari]: N/A

**Comment by aschnab** [comment]
The source of the problem seems to be the following line in `convertMedicationAdministrationDosageComponent`, which uses the general `convertType` method rather than something which is aware that `convertSimpleQuantity` rather than `convertQuantity` should be applied to an argument of type Quantity.

This suggests that the problem might apply not only to MedicationAdministration.dosage.rate, but to any attribute of a choice data type with SimpleQuantity as one of the options.
