### ISSUE TITLE
Error when executing operation $meta-add

### ISSUE THREAD

**Issue by seanmcilvenna** [jamesagnew/hapi-fhir#1313]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
When I execute $meta-add, I am getting the following error:
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: javax.persistence.NonUniqueResultException: query did not return a unique result: 3</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: javax.persistence.NonUniqueResultException: query did not return a unique result: 3"
        }
    ]
}
```

The server logs show the following:
```
2019-05-20 18:47:12.551 [http-nio-8080-exec-36] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:134] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: javax.persistence.NonUniqueResultException: query did not return a unique result: 3
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:265)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:288)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:228)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:362)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:263)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:973)
        at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:338)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1542)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
        at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor372.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:260)
        ... 33 common frames omitted
Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 3
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1585)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.getTagOrNull(BaseHapiFhirDao.java:647)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doMetaAdd(BaseHapiFhirResourceDao.java:531)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.metaAddOperation(BaseHapiFhirResourceDao.java:718)
        at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy182.metaAddOperation(Unknown Source)
        at ca.uhn.fhir.jpa.provider.dstu3.JpaResourceProviderDstu3.metaAdd(JpaResourceProviderDstu3.java:144)
        ... 37 common frames omitted
```

**To Reproduce**

POST /fhir/ImplementationGuide/us-core/$meta-add
```
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "meta",
      "valueMeta": {
        "security": [{
          "system": "https://trifolia-fhir.lantanagroup.com/security",
          "code": "everyone^read"
        }]
      }
    }
  ]
}
```

**Expected behavior**
Should have gotten a 200 OK.

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by seanmcilvenna** [comment]
Some more information...
It seems to be specifically related to Resource.meta.security tags.
If I update the resource via PUT /fhir/ImplementationGuide/XXX, where the resource I'm updating it with includes meta.security, I get the same exact error.

**Comment by seanmcilvenna** [comment]
And _more_ information...
I was able to copy the MySql database to my own local environment, and I ran hapi-fhir-jpaserver-starter in my own environment using IntelliJ. I was able to debug the line that was throwing the exception, and it throwing an exception when it executed this SQL:
```
select generatedAlias0 from TagDefinition as generatedAlias0 where ( generatedAlias0.myTagType=:param0 ) and ( generatedAlias0.mySystem=:param1 ) and ( generatedAlias0.myCode=:param2 )
```
It was expecting there to be 1 result, when instead there were 3.
After doing some digging/querying in the MySql database, I found that three resources had the same tag system and value, but there were three entries in the HFJ_TAG_DEF table:

| TAG_ID | TAG_CODE | TAG_DISPLAY | TAG_SYSTEM | TAG_TYPE |
| ------- | ----------- | -------------- | -------------- | ---------- |
| 102 | everyone^read | NULL | https://trifolia-fhir... | 2 |
| 103 | everyone^read | NULL | https://trifolia-fhir... | 2 |
| 104 | everyone^read | NULL | https://trifolia-fhir... | 2 |

I'm not sure how the same tag code got added to this table three different times... But, I was able to get past the error by removing two of three entries, and replacing their reference in HFJ_RES_TAG with the one TAG_ID that I left remaining.

**Comment by seanmcilvenna** [comment]
I wonder if this is a concurrency issue. If I had two resources saving with tags at the same time with the same code, would it produce two of the same HFJ_TAG_DEF entries?
