### ISSUE TITLE
Latest snapshot of server throws ConfigurationException: Search param telecom is of unexpected datatype

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#139]
ca.uhn.fhir.context.ConfigurationException: Search param telecom is of unexpected datatype: class ca.uhn.fhir.model.dstu2.composite.ContactPointDt
	at ca.uhn.fhir.jpa.dao.SearchParamExtractorDstu2.extractSearchParamTokens(SearchParamExtractorDstu2.java:470) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirDao.extractSearchParamTokens(BaseFhirDao.java:265) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirDao.updateEntity(BaseFhirDao.java:1040) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.doCreate(BaseFhirResourceDao.java:751) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.update(BaseFhirResourceDao.java:1748) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.update(BaseFhirResourceDao.java:1715) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.update(BaseFhirResourceDao.java:1710) ~[hapi-fhir-jpaserver-base-1.0-SNAPSHOT.jar:na]

**Comment by mochaholic** [comment]
My workaround to make the server work for now was to add another else-if block near line 470 in SearchParamExtractorDstu2.java to swallow ContactPointDt and avoid throwing the exception.

**Comment by jamesagnew** [comment]
Thanks for reporting! Fix coming up shortly.
