### ISSUE TITLE
The JAX-RS paths for find, findHistory, and findCompartment are ambiguous.

### ISSUE THREAD

**Issue by sethrylan** [jamesagnew/hapi-fhir#1402]
`_history` requests to `AbstractJaxRsResourceProvider` subclasses are routed to the wrong methods.

**To Reproduce**

Implement and call `_history` endpoints (type or instance) using `AbstractJaxRsResourceProvider`

```
  @History
  public IBundleProvider getHistoryForInstance(@IdParam IIdType theId, @Since Date theSince, @At DateRangeParam theAt, RequestDetails theRequestDetails) {
    return new SimpleBundleProvider();
  }
...
client.history().onInstance(new IdDt("Patient", 1L)).returnBundle(Bundle.class).execute();
```

**Expected behavior**
Request routed to `getHistoryForInstance`

**Results Seen**
```
Caused by: ca.uhn.fhir.rest.server.exceptions.NotImplementedOperationException: Operation not implemented
  at ca.uhn.fhir.jaxrs.server.util.JaxRsMethodBindings.getBinding(JaxRsMethodBindings.java:123)
  at ca.uhn.fhir.jaxrs.server.AbstractJaxRsResourceProvider.getBinding(AbstractJaxRsResourceProvider.java:325)
  at ca.uhn.fhir.jaxrs.server.AbstractJaxRsResourceProvider.execute(AbstractJaxRsResourceProvider.java:297)
  at ca.uhn.fhir.jaxrs.server.AbstractJaxRsResourceProvider.findCompartment(AbstractJaxRsResourceProvider.java:278)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
```

The `AbstractJaxRsResourceProvider.findCompartment` path (`/{id}/{compartment}`) is ambiguous to `/{id}/_history`

Similarly, a request for type history (`GET /Patient/_history`) will map to the resource path defined for `AbstractJaxRsResourceProvider.find`

**Environment**
 - HAPI FHIR Version 3.8.0 and 4.0.0-SNAPSHOT (see https://github.com/jamesagnew/hapi-fhir/pull/1404)

**Comment by bpgriner** [comment]
@jamesagnew can this be closed due to the merge of https://github.com/jamesagnew/hapi-fhir/pull/1404 ?

**Comment by jamesagnew** [comment]
Closing as #1404 was merged
