### ISSUE TITLE
upload-terminology command does not work for DSTU3. Fix this!

### ISSUE THREAD

**Issue by dmuylwyk** [jamesagnew/hapi-fhir#1408]
upload-terminology command does not work for DSTU3. Fix this!

To reproduce:

```bash
~/i/hapi-fhir-server $ java -jar ~/intellij-idea-workspace/hapi-fhir/hapi-fhir-cli/hapi-fhir-cli-app/target/hapi-fhir-cli.jar run-server -v dstu3
```

Add LOINC file and `loincupload.properties` to `~/intellij-idea-workspace/hapi-fhir-server/`.

Contents of `loincupload.properties`:

```
# This is the version identifier for the AnswerList file
answerlist.version=Loinc_2.66_AnswerFile_2.66

# This is the version identifier for uploaded ConceptMap resources
conceptmap.version=Loinc_2.66
```

```
~/i/hapi-fhir-server $ java -jar ~/intellij-idea-workspace/hapi-fhir/hapi-fhir-cli/hapi-fhir-cli-app/target/hapi-fhir-cli.jar upload-terminology -v dstu3 -t http://localhost:8080/baseDstu3 -u http://loinc.org -l -d ./Loinc_2.66.zip -d ./loincupload.properties
```

Here's the console output:

```bash
~/i/hapi-fhir-server $ java -jar ~/intellij-idea-workspace/hapi-fhir/hapi-fhir-cli/hapi-fhir-cli-app/target/hapi-fhir-cli.jar upload-terminology -v dstu3 -t http://localhost:8080/baseDstu3 -u http://loinc.org -l -d ./Loinc_2.66.zip -d ./loincupload.properties 
------------------------------------------------------------
🔥  HAPI FHIR 4.0.0-SNAPSHOT - Command Line Tool
------------------------------------------------------------
Process ID                      : 30604@simpatico-mbp
Max configured JVM memory (Xmx) : 3.5GB
Detected Java version           : 1.8.0_201
------------------------------------------------------------
2019-08-01 09:44:52.648 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2019-08-01 09:44:53.195 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.context.ConfigurationException: This context is for FHIR version "DSTU3" but the class "org.hl7.fhir.r4.model.CodeSystem" is for version "R4"
	at ca.uhn.fhir.context.RuntimeResourceDefinition.<init>(RuntimeResourceDefinition.java:69)
	at ca.uhn.fhir.context.ModelScanner.scanResource(ModelScanner.java:320)
	at ca.uhn.fhir.context.ModelScanner.scan(ModelScanner.java:166)
	at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:114)
	at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:69)
	at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:759)
	at ca.uhn.fhir.context.FhirContext.scanResourceType(FhirContext.java:745)
	at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:385)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1141)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:110)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:251)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2019-08-01 09:44:53.197 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

**Acceptance Criteria:**
* upload-terminology command works for DSTU3. It's fixed!

**Comment by dmuylwyk** [comment]
Working branch: [1408-upload-terminology-command-does-not-work-for-dstu3-fix-this](https://github.com/jamesagnew/hapi-fhir/tree/1408-upload-terminology-command-does-not-work-for-dstu3-fix-this)

**Comment by dmuylwyk** [comment]
Pull request: https://github.com/jamesagnew/hapi-fhir/pull/1412

**Comment by dmuylwyk** [comment]
Resolved.
