### ISSUE TITLE
No transactional EntityManager available

### ISSUE THREAD

**Issue by WaldekPac** [jamesagnew/hapi-fhir#1437]
HAPI FHIR Version 4.0.0

I uses BaseJavaConfigR4 configuration with spring boot and mysql database.

Our server use RequestValidatingInterceptor with myInstanceValidatorR4 validation module.

When creating Encounter resource with coding, hapifihr server throw an exception

```
Caused by: java.lang.IllegalStateException: No transactional EntityManager available
    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:282) ~[spring-orm-5.1.7.RELEASE.jar:5.1.7.RELEASE]
    at com.sun.proxy.$Proxy155.unwrap(Unknown Source) ~[na:na]
    at org.hibernate.search.jpa.Search.getSession(Search.java:55) ~[hibernate-search-orm-5.11.1.Final.jar:5.11.1.Final]
    at org.hibernate.search.jpa.Search.getFullTextEntityManager(Search.java:49) ~[hibernate-search-orm-5.11.1.Final.jar:5.11.1.Final]
    at ca.uhn.fhir.jpa.term.BaseHapiTerminologySvcImpl.expandValueSetHandleIncludeOrExclude(BaseHapiTerminologySvcImpl.java:527) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at ca.uhn.fhir.jpa.term.BaseHapiTerminologySvcImpl.expandValueSet(BaseHapiTerminologySvcImpl.java:494) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at ca.uhn.fhir.jpa.term.BaseHapiTerminologySvcImpl.expandValueSet(BaseHapiTerminologySvcImpl.java:470) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at ca.uhn.fhir.jpa.term.HapiTerminologySvcR4.expandValueSet(HapiTerminologySvcR4.java:150) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at ca.uhn.fhir.jpa.term.HapiTerminologySvcR4$$FastClassBySpringCGLIB$$1a84fb50.invoke(<generated>) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]
    at ca.uhn.fhir.jpa.term.HapiTerminologySvcR4$$EnhancerBySpringCGLIB$$32957cc6.expandValueSet(<generated>) ~[hapi-fhir-jpaserver-base-4.0.0.jar:na]
    at org.hl7.fhir.r4.hapi.validation.ValidationSupportChain.expandValueSet(ValidationSupportChain.java:53) ~[hapi-fhir-validation-4.0.0.jar:na]
    at org.hl7.fhir.r4.hapi.validation.CachingValidationSupport.expandValueSet(CachingValidationSupport.java:36) ~[hapi-fhir-validation-4.0.0.jar:na]
    at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.expandVS(HapiWorkerContext.java:329) ~[hapi-fhir-structures-r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.terminologies.ValueSetExpanderSimple.doServerIncludeCodes(ValueSetExpanderSimple.java:445) ~[org.hl7.fhir.r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.terminologies.ValueSetExpanderSimple.includeCodes(ValueSetExpanderSimple.java:437) ~[org.hl7.fhir.r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.terminologies.ValueSetExpanderSimple.handleCompose(ValueSetExpanderSimple.java:387) ~[org.hl7.fhir.r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.terminologies.ValueSetExpanderSimple.doExpand(ValueSetExpanderSimple.java:321) ~[org.hl7.fhir.r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.terminologies.ValueSetExpanderSimple.expand(ValueSetExpanderSimple.java:291) ~[org.hl7.fhir.r4-4.0.0.jar:na]
    at org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext.expand(HapiWorkerContext.java:309) ~[hapi-fhir-structures-r4-4.0.0.jar:na]
```

ValueSet and CodeSystem resources was added to server. 

ValueSet url = https://example.com/fhir/ValueSet/MyMedicalEventClass
CodeSystem url = https://example.com/fhir/CodeSystem/MyMedicalEventCodeSystemClass

In Encounter I put class node

```
   <class>
      <system value="https://example.com/fhir/CodeSystem/MyMedicalEventCodeSystemClass"/>
      <code value="1"/>
      <display value="Name 1"/>
   </class>
```

**Comment by WaldekPac** [comment]
This issue does not occur in version 4.1.0-SNAPSHOT - Rev 8728a14382.

Thanks for your help.
