### ISSUE TITLE
database-migration does not find resources

### ISSUE THREAD

**Issue by cuhland** [jamesagnew/hapi-fhir#1542]
**Describe the bug**
The server does not start after the database migration from 3.8.0 to 4.0.0.

>org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in com.cerner.augero.fhir.test.server.FhirServerConfig: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
> 
>Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable

I am using hibernate with a postgreSQL database with this Config:
```java
@Override
@Bean()
public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
    LocalContainerEntityManagerFactoryBean retVal = new LocalContainerEntityManagerFactoryBean();
    retVal.setJpaVendorAdapter(new org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter());
    retVal.setPersistenceProvider(new HibernatePersistenceProvider());
    retVal.setDataSource(dataSource());
    retVal.setPersistenceUnitName("HAPI_PU");
    retVal.setPackagesToScan("ca.uhn.fhir.jpa.entity");

    retVal.setJpaProperties(jpaProperties());
    return retVal;
}

private Properties jpaProperties() {
    Properties extraProperties = new Properties();
    extraProperties.put("hibernate.dialect", PostgreSQL95Dialect.class.getName());
    extraProperties.put("hibernate.format_sql", "true");
    extraProperties.put("hibernate.show_sql", "false");
    extraProperties.put("hibernate.hbm2ddl.auto", "update");
    extraProperties.put("hibernate.jdbc.batch_size", "20");
    extraProperties.put("hibernate.cache.use_query_cache", "false");
    extraProperties.put("hibernate.cache.use_second_level_cache", "false");
    extraProperties.put("hibernate.cache.use_structured_entries", "false");
    extraProperties.put("hibernate.cache.use_minimal_puts", "false");
    extraProperties.put("hibernate.search.model_mapping", LuceneSearchMappingFactory.class.getName());
    extraProperties.put("hibernate.search.default.directory_provider", "filesystem");
    extraProperties.put("hibernate.search.default.indexBase", "target/lucenefiles");
    extraProperties.put("hibernate.search.lucene_version", "LUCENE_CURRENT");
    return extraProperties;
}
```

**Log**
```
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fhir-test-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory XXX\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ fhir-test-server ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fhir-test-server ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-war-plugin:3.2.0:war (default-war) @ fhir-test-server ---
[INFO] Packaging webapp
[INFO] Assembling webapp [fhir-test-server] in [XXX\target\hapi-fhir-test-server]
[INFO] Processing war project
[INFO] Copying webapp resources [XXX\src\main\webapp]
[INFO] Processing overlay [ id ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay]
[INFO] Webapp assembled in [2290 msecs]
[INFO] Building war: XXX\target\hapi-fhir-test-server.war
[INFO]
[INFO] <<< tomcat7-maven-plugin:2.2:run-war (default-cli) < package @ fhir-test-server <<<
[INFO]
[INFO]
[INFO] --- tomcat7-maven-plugin:2.2:run-war (default-cli) @ fhir-test-server ---
[INFO] Running war on http://localhost:8080/fhir-test-server
[INFO] Creating Tomcat server configuration at XXX\target\tomcat
[INFO] create webapp with contextPath: /fhir-test-server
Okt 15, 2019 2:35:31 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-bio-8080"]
Okt 15, 2019 2:35:31 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service Tomcat
Okt 15, 2019 2:35:31 PM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/7.0.47
Okt 15, 2019 2:35:32 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFORMATION: validateJarFile(XXX\target\hapi-fhir-test-server\WEB-INF\lib\javax.el-3.0.0.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/el/Expression.class
Okt 15, 2019 2:35:32 PM org.apache.catalina.deploy.WebXml orderWebFragments
WARNUNG: Used a wrong fragment name fhirServlet at web.xml absolute-ordering tag!
Okt 15, 2019 2:35:33 PM org.apache.catalina.core.ApplicationContext log
INFORMATION: Initializing Spring root WebApplicationContext
[INFO] Root WebApplicationContext: initialization started
[INFO] Successfully resolved class for [xxx.xxx.xxx.FhirServerConfig]
[INFO] Bootstrapping Spring Data repositories in DEFAULT mode.
[INFO] Finished Spring Data repository scanning in 561ms. Found 36 repository interfaces.
[INFO] Bootstrapping Spring Data repositories in DEFAULT mode.
[INFO] Finished Spring Data repository scanning in 136ms. Found 36 repository interfaces.
[INFO] Bootstrapping Spring Data repositories in DEFAULT mode.
[INFO] Finished Spring Data repository scanning in 150ms. Found 36 repository interfaces.
[INFO] Bootstrapping Spring Data repositories in DEFAULT mode.
[INFO] Finished Spring Data repository scanning in 172ms. Found 36 repository interfaces.
[INFO] HHH000204: Processing PersistenceUnitInfo [name: HAPI_PU]
[INFO] HHH000412: Hibernate Core {5.4.2.Final}
[INFO] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
[INFO] HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL94Dialect
[WARNING] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory'
defined in xxx.xxx.xxx.FhirServerConfig: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
[ERROR] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in xxx.xxx.xxx.FhirServerConfig: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean (AbstractAutowireCapableBeanFactory.java:1778)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean (AbstractAutowireCapableBeanFactory.java:593)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory.java:515)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0 (AbstractBeanFactory.java:320)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton (DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean (AbstractBeanFactory.java:318)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean (AbstractBeanFactory.java:199)
    at org.springframework.context.support.AbstractApplicationContext.getBean (AbstractApplicationContext.java:1105)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization (AbstractApplicationContext.java:867)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:549)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext (ContextLoader.java:409)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext (ContextLoader.java:291)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized (ContextLoaderListener.java:103)
    at org.apache.catalina.core.StandardContext.listenerStart (StandardContext.java:4939)
    at org.apache.catalina.core.StandardContext.startInternal (StandardContext.java:5434)
    at org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call (ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call (ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
    at org.hibernate.cfg.ToOneFkSecondPass.doSecondPass (ToOneFkSecondPass.java:97)
    at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processEndOfQueue (InFlightMetadataCollectorImpl.java:1815)
    at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processFkSecondPassesInOrder (InFlightMetadataCollectorImpl.java:1759)
    at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses (InFlightMetadataCollectorImpl.java:1646)
    at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete (MetadataBuildingProcess.java:286)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata (EntityManagerFactoryBuilderImpl.java:900)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build (EntityManagerFactoryBuilderImpl.java:931)
    at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory (HibernatePersistenceProvider.java:141)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory (LocalContainerEntityManagerFactoryBean.java:365)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory (AbstractEntityManagerFactoryBean.java:390)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet (AbstractEntityManagerFactoryBean.java:377)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet (LocalContainerEntityManagerFactoryBean.java:341)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods (AbstractAutowireCapableBeanFactory.java:1837)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean (AbstractAutowireCapableBeanFactory.java:1774)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean (AbstractAutowireCapableBeanFactory.java:593)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory.java:515)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0 (AbstractBeanFactory.java:320)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton (DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean (AbstractBeanFactory.java:318)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean (AbstractBeanFactory.java:199)
    at org.springframework.context.support.AbstractApplicationContext.getBean (AbstractApplicationContext.java:1105)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization (AbstractApplicationContext.java:867)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:549)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext (ContextLoader.java:409)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext (ContextLoader.java:291)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized (ContextLoaderListener.java:103)
    at org.apache.catalina.core.StandardContext.listenerStart (StandardContext.java:4939)
    at org.apache.catalina.core.StandardContext.startInternal (StandardContext.java:5434)
    at org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call (ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call (ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Okt 15, 2019 2:36:02 PM org.apache.catalina.core.StandardContext listenerStart
SCHWERWIEGEND: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in xxx.xxx.xxx.FhirServerConfig: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on ca.uhn.fhir.jpa.entity.SubscriptionTable.mySubscriptionResource references an unknown entity: ca.uhn.fhir.jpa.model.entity.ResourceTable
        at org.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processEndOfQueue(InFlightMetadataCollectorImpl.java:1815)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processFkSecondPassesInOrder(InFlightMetadataCollectorImpl.java:1759)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1646)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:286)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:900)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:931)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
        ... 21 more

Okt 15, 2019 2:36:02 PM org.apache.catalina.core.StandardContext startInternal
SCHWERWIEGEND: Error listenerStart
Okt 15, 2019 2:36:02 PM org.apache.catalina.core.StandardContext startInternal
SCHWERWIEGEND: Context [/fhir-test-server] startup failed due to previous errors
Okt 15, 2019 2:36:02 PM org.apache.catalina.core.ApplicationContext log
INFORMATION: Closing Spring root WebApplicationContext
Okt 15, 2019 2:36:02 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SCHWERWIEGEND: The web application [/fhir-test-server] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Okt 15, 2019 2:36:02 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SCHWERWIEGEND: The web application [/fhir-test-server] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the
JDBC Driver has been forcibly unregistered.
Okt 15, 2019 2:36:02 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-bio-8080"]

```

**Expected behavior**

After database-migration from 3.8.0 to 4.0.0 the server should start.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.0.0
 - OS: Windows

**Comment by jamesagnew** [comment]
This looks like a classpath issue. Have you done a clean build?

**Comment by cuhland** [comment]
Thanks for the feedback. The database-migration was okay. It was a problem with the 'old' [hapi-fhir-jpaserver-example](https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-jpaserver-example). 

The [hapi-fhir-jpaserver-starter](https://github.com/hapifhir/hapi-fhir-jpaserver-starter) starts.
