### ISSUE TITLE
MapType error uploading Loinc_2.67 with HAPI FHIR 4.1.0

### ISSUE THREAD

**Issue by djvreeman** [jamesagnew/hapi-fhir#1649]
**Bug**
Using CLI 4.1.0 to upload the latest LOINC content fails with a "Mapping for MapType not found" error.

**Steps to reproduce**
Add a `loincupload.properties` file to the standard LOINC release zip file `Loinc_2.67.zip`
Then use the upload-terminology function:
`sudo java -Xmx2500m -jar hapi-fhir-cli.jar upload-terminology -d loinc/Loinc_2.67.zip -t http://localhost:8080/baseR4/ -v r4 -u http://loinc.org`

**Error message that results:**

```
2019-12-26 15:57:48.01 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2019-12-26 16:04:18.222 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: java.lang.IllegalArgumentException: Mapping for MapType not found, expected one of [PartNumber, PartName, PartTypeName, ExtCodeId, ExtCodeDisplayName, ExtCodeSystem, Equivalence, ContentOrigin, ExtCodeSystemVersion, ExtCodeSystemCopyrightNotice]</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.IllegalArgumentException: Mapping for MapType not found, expected one of [PartNumber, PartName, PartTypeName, ExtCodeId, ExtCodeDisplayName, ExtCodeSystem, Equivalence, ContentOrigin, ExtCodeSystemVersion, ExtCodeSystemCopyrightNotice]"
    }
  ]
}
2019-12-26 16:04:18.597 [main] ERROR ca.uhn.fhir.cli.App Error during execution: 
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 Server Error: Failed to call access method: java.lang.IllegalArgumentException: Mapping for MapType not found, expected one of [PartNumber, PartName, PartTypeName, ExtCodeId, ExtCodeDisplayName, ExtCodeSystem, Equivalence, ContentOrigin, ExtCodeSystemVersion, ExtCodeSystemCopyrightNotice]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
	at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1173)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:204)
	at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:113)
	at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:251)
	at ca.uhn.fhir.cli.App.main(App.java:43)
2019-12-26 16:04:18.788 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

**Comment by jamesagnew** [comment]
Thanks @djvreeman for reporting! Looks like `MapType` for replaced with `equivalence`. This was an easy fix.
