### ISSUE TITLE
Loading XML -based profiles with xsi:schemaLocation and validation=true

### ISSUE THREAD

**Issue by bkaney** [jamesagnew/hapi-fhir#1676]
This is an elaboration of the bug entered here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/76

**Describe the bug**

When setting the validation to true, e.g. `validation.requests.enabled=true`, then creating XML-based structure definition, we get an `HTTP 422 Unprocessable Entity: Undefined attribute '@xsi:schemaLocation' on StructureDefinition for type StructureDefinition`. The `$validate` operation for the same XML is successful.

If validation is off, e.g.: `validation.requests.enabled=false`, the POST to create is a successful StructureDefinition.

**Expected Behavior**
Create the StructureDefinition is successful.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.0.0 and 4.1.0

---
**HTTP Response**
```
<OperationOutcome xmlns="http://hl7.org/fhir">
   <text>
      <status value="generated"/>
      <div xmlns="http://www.w3.org/1999/xhtml">
         <h1>Operation Outcome</h1>
         <table border="0">
            <tr>
               <td style="font-weight: bold;">ERROR</td>
               <td>[/f:StructureDefinition, Line 2, Col 178]</td>
               <td>
                  <pre>Undefined attribute '@xsi:schemaLocation' on StructureDefinition for type StructureDefinition (properties = [StructureDefinition.id, StructureDefinition.meta, StructureDefinition.implicitRules, StructureDefinition.language, StructureDefinition.text, StructureDefinition.contained, StructureDefinition.extension, StructureDefinition.modifierExtension, StructureDefinition.url, StructureDefinition.identifier, StructureDefinition.version, StructureDefinition.name, StructureDefinition.title, StructureDefinition.status, StructureDefinition.experimental, StructureDefinition.date, StructureDefinition.publisher, StructureDefinition.contact, StructureDefinition.description, StructureDefinition.useContext, StructureDefinition.jurisdiction, StructureDefinition.purpose, StructureDefinition.copyright, StructureDefinition.keyword, StructureDefinition.fhirVersion, StructureDefinition.mapping, StructureDefinition.kind, StructureDefinition.abstract, StructureDefinition.context, StructureDefinition.contextInvariant, StructureDefinition.type, StructureDefinition.baseDefinition, StructureDefinition.derivation, StructureDefinition.snapshot, StructureDefinition.differential])</pre>
               </td> 
            </tr> 
            <tr> 
               <td style="font-weight: bold;">WARNING</td> 
               <td>[StructureDefinition, Line 2, Col 178]</td> 
               <td>
                  <pre>dom-6: A resource should have narrative for robust management [text.div.exists()]</pre>
               </td> 
            </tr> 
         </table> 
      </div>
   </text>
   <issue>
      <severity value="error"/>
      <code value="processing"/>
      <diagnostics value="Undefined attribute '@xsi:schemaLocation' on StructureDefinition for type StructureDefinition (properties = [StructureDefinition.id, StructureDefinition.meta, StructureDefinition.implicitRules, StructureDefinition.language, StructureDefinition.text, StructureDefinition.contained, StructureDefinition.extension, StructureDefinition.modifierExtension, StructureDefinition.url, StructureDefinition.identifier, StructureDefinition.version, StructureDefinition.name, StructureDefinition.title, StructureDefinition.status, StructureDefinition.experimental, StructureDefinition.date, StructureDefinition.publisher, StructureDefinition.contact, StructureDefinition.description, StructureDefinition.useContext, StructureDefinition.jurisdiction, StructureDefinition.purpose, StructureDefinition.copyright, StructureDefinition.keyword, StructureDefinition.fhirVersion, StructureDefinition.mapping, StructureDefinition.kind, StructureDefinition.abstract, StructureDefinition.context, StructureDefinition.contextInvariant, StructureDefinition.type, StructureDefinition.baseDefinition, StructureDefinition.derivation, StructureDefinition.snapshot, StructureDefinition.differential])"/>
      <location value="/f:StructureDefinition"/>
      <location value="Line 2, Col 178"/>
   </issue>
   <issue>
      <severity value="warning"/>
      <code value="processing"/>
      <diagnostics value="dom-6: A resource should have narrative for robust management [text.div.exists()]"/>
      <location value="StructureDefinition"/>
      <location value="Line 2, Col 178"/>
   </issue>
</OperationOutcome>
```

**Full server backtrace**
```
2020-01-19 02:53:00.278 [qtp580024961-14] INFO  fhirtest.access [LoggingInterceptor.java:175] Path[/fhir] Source[] Operation[metadata  ] UA[HAPI-FHIR/4.1.0 (FHIR Client; FHIR 4.0.0/R4; apache)] Params[?_pretty=true] ResponseEncoding[JSON]
2020-01-19 02:53:00.329 [qtp580024961-15] WARN  c.u.fhir.parser.LenientErrorHandler [LenientErrorHandler.java:143] Unknown attribute 'schemaLocation' found while parsing
2020-01-19 02:53:00.335 [qtp580024961-15] WARN  c.u.fhir.parser.LenientErrorHandler [LenientErrorHandler.java:143] Unknown attribute 'schemaLocation' found while parsing
2020-01-19 02:53:00.348 [qtp580024961-19] INFO  ca.uhn.fhir.validation.FhirValidator [SchematronProvider.java:42] Ph-schematron library not found on classpath, will not attempt to perform schematron validation
2020-01-19 02:53:01.328 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:186] Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/r4/model/valueset/valuesets.xml
2020-01-19 02:53:01.668 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:186] Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/r4/model/valueset/v2-tables.xml
2020-01-19 02:53:01.939 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:186] Loading CodeSystem/ValueSet from classpath: /org/hl7/fhir/r4/model/valueset/v3-codesystems.xml
2020-01-19 02:53:02.111 [qtp580024961-19] INFO  fhirtest.access [LoggingInterceptor.java:160] ERROR - POST http://localhost:8080/hapi/fhir/StructureDefinition
2020-01-19 02:53:02.145 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:227] Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-resources.xml
2020-01-19 02:53:02.648 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:227] Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-types.xml
2020-01-19 02:53:02.688 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:227] Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-others.xml
2020-01-19 02:53:02.895 [qtp580024961-19] INFO  o.h.f.r.h.c.DefaultProfileValidationSupport [DefaultProfileValidationSupport.java:227] Loading structure definitions from classpath: /org/hl7/fhir/r4/model/extension/extension-definitions.xml
2020-01-19 02:53:03.211 [qtp580024961-15] WARN  ca.uhn.fhir.to.BaseController [BaseController.java:288] Failed to invoke server
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: Undefined attribute '@xsi:schemaLocation' on StructureDefinition for type StructureDefinition (properties = [StructureDefinition.id, StructureDefinition.meta, StructureDefinition.implicitRules, StructureDefinition.language, StructureDefinition.text, StructureDefinition.contained, StructureDefinition.extension, StructureDefinition.modifierExtension, StructureDefinition.url, StructureDefinition.identifier, StructureDefinition.version, StructureDefinition.name, StructureDefinition.title, StructureDefinition.status, StructureDefinition.experimental, StructureDefinition.date, StructureDefinition.publisher, StructureDefinition.contact, StructureDefinition.description, StructureDefinition.useContext, StructureDefinition.jurisdiction, StructureDefinition.purpose, StructureDefinition.copyright, StructureDefinition.keyword, StructureDefinition.fhirVersion, StructureDefinition.mapping, StructureDefinition.kind, StructureDefinition.abstract, StructureDefinition.context, StructureDefinition.contextInvariant, StructureDefinition.type, StructureDefinition.baseDefinition, StructureDefinition.derivation, StructureDefinition.snapshot, StructureDefinition.differential])
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
        at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:581)
        at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:536)
        at ca.uhn.fhir.to.Controller.doActionCreateOrValidate(Controller.java:577)
        at ca.uhn.fhir.to.Controller.actionCreate(Controller.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.lang.Thread.run(Thread.java:748)
2020-01-19 02:53:03.235 [qtp580024961-15] INFO  ca.uhn.fhir.to.Controller [Controller.java:593] [server=home] - Created resource of type StructureDefinition

```

**Example Structure Definition**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<StructureDefinition xmlns="http://hl7.org/fhir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hl7.org/fhir http://build.fhir.org/device.xsd">
	<id value="us-core-birthsex"/>
	<url value="http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"/>
	<version value="1.0.1"/>
	<name value="USCoreBirthSexExtension"/>
	<title value="US Core Birth Sex Extension"/>
	<status value="active"/>
	<date value="2019-05-21"/>
	<publisher value="HL7 US Realm Steering Committee"/>
	<contact>
		<telecom>
			<system value="url"/>
			<value value="http://www.healthit.gov"/>
		</telecom>
	</contact>
	<description value="A code classifying the person&#39;s sex assigned at birth  as specified by the [Office of the National Coordinator for Health IT (ONC)](https://www.healthit.gov/newsroom/about-onc). This extension aligns with the C-CDA Birth Sex Observation (LOINC 76689-9)."/>
	<fhirVersion value="4.0.1"/>
	<mapping>
		<identity value="rim"/>
		<uri value="http://hl7.org/v3"/>
		<name value="RIM Mapping"/>
	</mapping>
	<kind value="complex-type"/>
	<abstract value="false"/>
	<context>
		<type value="element"/>
		<expression value="Patient"/>
	</context>
	<type value="Extension"/>
	<baseDefinition value="http://hl7.org/fhir/StructureDefinition/Extension"/>
	<derivation value="constraint"/>
	<differential>
		<element id="Extension">
			<path value="Extension"/>
			<definition value="A code classifying the person&#39;s sex assigned at birth  as specified by the [Office of the National Coordinator for Health IT (ONC)](https://www.healthit.gov/newsroom/about-onc)."/>
			<comment value="The codes required are intended to present birth sex (i.e., the sex recorded on the patient’s birth certificate) and not gender identity or reassigned sex."/>
			<min value="0"/>
			<max value="1"/>
			<isModifier value="false"/>
			<mapping>
				<identity value="rim"/>
				<map value="player[classCode=PSN|ANM and determinerCode=INSTANCE]/administrativeGender"/>
			</mapping>
			<mapping>
				<identity value="iso11179"/>
				<map value=".patient.administrativeGenderCode"/>
			</mapping>
		</element>
		<element id="Extension.url">
			<path value="Extension.url"/>
			<fixedUri value="http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"/>
		</element>
		<element id="Extension.valueCode">
			<path value="Extension.valueCode"/>
			<min value="0"/>
			<max value="1"/>
			<type>
				<code value="code"/>
			</type>
			<binding>
				<strength value="required"/>
				<description value="Code for sex assigned at birth"/>
				<valueSet value="http://hl7.org/fhir/us/core/ValueSet/birthsex"/>
			</binding>
		</element>
	</differential>
</StructureDefinition>
```

**Comment by bkaney** [comment]
This can be reproduced with any XML-based structure definition that declares xsi:schemaLocation, e.g.: in the resource tag (such as US Core):
```
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hl7.org/fhir http://build.fhir.org/device.xsd"
```
