### ISSUE TITLE
Value Set expand operation return null point exception when the value set EXPANSION_STATUS is expanded

### ISSUE THREAD

**Issue by HananAwwad** [jamesagnew/hapi-fhir#1780]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Value Set expand operation return null point exception when the value set EXPANSION_STATUS is expanded

**To Reproduce**
1. Create Value set
PUT: fhir/ValueSet/testValueSet
  {"resourceType": "ValueSet",
  "id": "testValueSet",
  "text": {
    "status": "generated",
    "div": ""
  },
  "url": "test.com/testValueSet",
  "name": "testValueSet",
  "title": "testValueSet",
  "status": "active",
  "experimental": false,
  "contact": [
    {
      "telecom": [
        {
          "system": "url",
          "value": "http://hl7.org/fhir"
        },
        {
          "system": "email",
          "value": "fhir@lists.hl7.org"
        }
      ]
    }
  ],
  "immutable": true,
  "compose": {
    "include": [
      {
        "system": "http://hl7.org/fhir/action-cardinality-behavior"
      }
    ]
  }
}

2. Get fhir/ValueSet/testValueSet/$expand 
this result will work as expected after some times the quartz job will run in background to expand all the concepts and store it in TRM_VALUESET_CONCEPT, then it will store the status to EXPANSION_STATUS in TRM_VALUESET as EXPANDED 

3- Get fhir/ValueSet/testValueSet/$expand and  See error

[http-nio-8081-exec-7] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:136] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.NullPointerException
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:244)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:319)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:245)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:382)
        at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:294)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:991)
        at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:336)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1675)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:239)
        ... 30 common frames omitted
Caused by: java.lang.NullPointerException: null
        at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandConcepts(BaseTermReadSvcImpl.java:403)
        at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.populateExpansionComponent(BaseTermReadSvcImpl.java:386)
        at ca.uhn.fhir.jpa.term.BaseTermReadSvcImpl.expandValueSet(BaseTermReadSvcImpl.java:366)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Expected behavior**
Return the concepts returned from the value set either it's status is expanded or not_expanded.

**Environment :**
 - HAPI FHIR 4.2.0
 - OS: windows10 and ubuntu  18.04
 - Browser: PostMan

**Additional context**
FhirContext R4

**Comment by jamesagnew** [comment]
This is fixed in current snapshot

**Comment by HananAwwad** [comment]
Thanks for your update, will pull the new snapshot
