### ISSUE TITLE
DiagnosticReport with presentedForm data containing base64Binary does not import when using MS SQL as DB for HAPI

### ISSUE THREAD

**Issue by petermicuch** [jamesagnew/hapi-fhir#1845]
**Describe the bug**
I have HAPI server build with connector to MS SQL database (using SQL Server 2019 and 2017, version does not matter).
When I am trying to post [test_bundle.zip](https://github.com/jamesagnew/hapi-fhir/files/4623252/test_bundle.zip) containing DiagnosticReport that contains PDF as base64Binary in presentedForm.data, I get [SQLServerException](https://github.com/jamesagnew/hapi-fhir/files/4623245/error_log.txt). Posting report without base64Binary data but with e.g. presentedForm.url works fine. Also other resources are imported nicely.
This problem is not there when using built in Derby or MySQL databases.

**To Reproduce**
1. Spin up HAPI server with connection to SQL Server 2017 or 2019 (I believe version does not matter). I tried both, dockerized and Windows installed SQL Server.
2. Try to post test_bundle.json from attachment to that HAPI server.
3. Exception occurs (see full log [error_log.txt](https://github.com/jamesagnew/hapi-fhir/files/4623245/error_log.txt)).
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The stream value is not the specified length. The specified length was 0, the actual length is 126á438.
        at com.microsoft.sqlserver.jdbc.TDSWriter.error(IOBuffer.java:4008)
        at com.microsoft.sqlserver.jdbc.TDSWriter.writeStream(IOBuffer.java:3837)
        at com.microsoft.sqlserver.jdbc.TDSWriter.writeRPCInputStream(IOBuffer.java:6090)
        at com.microsoft.sqlserver.jdbc.DTV$SendByRPCOp.execute(dtv.java:1406)
        at com.microsoft.sqlserver.jdbc.DTV.executeOp(dtv.java:1873)
        at com.microsoft.sqlserver.jdbc.DTV.sendByRPC(dtv.java:1915)
        at com.microsoft.sqlserver.jdbc.Parameter.sendByRPC(Parameter.java:1156)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.sendParamsByRPC(SQLServerPreparedStatement.java:695)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doPrepExec(SQLServerPreparedStatement.java:1045)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:2781)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2665)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2066)
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:242)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:119)
        ... 121 common frames omitted
```
**Expected behavior**
I expect the bundle to be imported without errors, just as it imports in case of built in Derby or MySQL databases.

**Environment**
 - HAPI FHIR 4.1.0 REST Server
 - Windows, Linux (docker container jetty:9-jre8-alpine)
 - Chrome

**Comment by petermicuch** [comment]
Some additional details:
- I also tried with latest HAPI FHIR version 4.2.0 - Rev 8491707942 - the same issue is observed there
- I did build my HAPI server using https://github.com/hapifhir/hapi-fhir-jpaserver-starter project, added mssql-jdbc into pom file in order to be able to use MSSQL and modified properties file accordingly

**Comment by petermicuch** [comment]
Tested with  HAPI FHIR version 5.0.0 - Rev 813d82e5fa - issue is still present.
