### ISSUE TITLE
Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10

### ISSUE THREAD

**Issue by rcampbel3** [jamesagnew/hapi-fhir#190]
mvn install fails on clean git clone on Ubuntu 14.04 x64

# mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-54-generic", arch: "amd64", family: "unix"

with...

[ERROR]   The project ca.uhn.hapi.fhir:hapi-fhir-base-testmindeps-server:1.1-SNAPSHOT (/home/ross/hapi-fhir/hapi-fhir-base-test-mindeps-server/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]

running 'mvn -e install', I get:

[FATAL] Non-resolvable parent POM: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ line 210, column 12
[WARNING] 'parent.relativePath' points at ca.uhn.hapi.fhir:hapi-fhir instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 8, column 10
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ line 143, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ line 160, column 12
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.eclipse.jetty:jetty-servlet:jar -> duplicate declaration of version ${jetty_version} @ line 199, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-war-plugin is missing. @ line 216, column 12

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project ca.uhn.hapi.fhir:hapi-fhir-base-testmindeps-server:1.1-SNAPSHOT (/home/ross/hapi-fhir/hapi-fhir-base-test-mindeps-server/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:813)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:685)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:495)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
	... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir:pom:1.1-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
	... 28 more

**Comment by jamesagnew** [comment]
Hi @rcampbel3 , that's strange. The build isn't failing in this way for me, but I had a look at the subproject that is failing for you and it does indeed have a bad parent pom.xml reference in it. I've just committed https://github.com/jamesagnew/hapi-fhir/commit/38338643bd8793590fe6bf1696f7fdce73325814 to fix that, so if you pull hopefully it should be ok now.

I'm using Maven 3.2, so possibly it's a bit more forgiving (the version you're using should be fine).

BTW, thanks for a very complete bug report! :) Please feel free to reopen if this doesn't resolve your issue.
