### ISSUE TITLE
GenericClient fail to deserialize dtsu2 bundle containing entries with links

### ISSUE THREAD

**Issue by joel-costigliola** [jamesagnew/hapi-fhir#191]
I'm writing a rest application providing DSTU2 observations, on the server side I return a bundle containing all the observations matching the client search criteria.
I use Bundle.Entry links to add some contextual information to let the requester knows if he can edit the returned observations (one link per entries).

It does not seem to be possible to get a dstu2 bundle from hapi-fhir `GenericClient` but note that I'm able to query the bundle from Chrome Postman rest client, it gives me this response:
```xml
<Bundle 
    xmlns="http://hl7.org/fhir">
    <id value="487d3669-0e1c-4867-b124-400d1849548d"></id>
    <type value="searchset"></type>
    <base value="http://localhost:19080/fhir/dstu1"></base>
    <link>
        <relation value="just trying add link"></relation>
        <url value="blarion"></url>
    </link>
    <link>
        <relation value="self"></relation>
        <url value="http://localhost:19080/fhir/dstu1/Observation?subject.identifier=puppet|CLONE-AA102"></url>
    </link>
    <entry>
        <link>
            <relation value="orionhealth.edit"></relation>
            <url value="Observation"></url>
        </link>
        <resource>
            <Observation 
                xmlns="http://hl7.org/fhir">
                <id value="0d87f02c-da2c-4551-9ead-2956f0165a4f"></id>
                <extension url="http://orionhealth.com/fhir/extensions#created-by"></extension>
                <extension url="http://orionhealth.com/fhir/extensions#last-modified-by"></extension>
                <extension url="http://orionhealth.com/fhir/extensions#received-instant">
                    <valueInstant value="2015-06-25T17:08:47.190+12:00"></valueInstant>
                </extension>
                <code>
                    <coding>
                        <system value="http://loinc.org"></system>
                        <code value="8867-4"></code>
                    </coding>
                </code>
                <valueString value="observationValue"></valueString>
                <status value="final"></status>
                <reliability value="ok"></reliability>
                <subject>
                    <reference value="Patient/INGE6TSFFVAUCMJQGJAHA5LQOBSXI"></reference>
                </subject>
            </Observation>
        </resource>
    </entry>
    <entry>
        <link>
            <relation value="orionhealth.edit"></relation>
            <url value="Observation"></url>
        </link>
        <resource>
            <Observation 
                xmlns="http://hl7.org/fhir">
                <id value="c54ac0cc-a99f-40aa-9541-c5aa853a2e88"></id>
                <extension url="http://orionhealth.com/fhir/extensions#created-by"></extension>
                <extension url="http://orionhealth.com/fhir/extensions#last-modified-by"></extension>
                <extension url="http://orionhealth.com/fhir/extensions#received-instant">
                    <valueInstant value="2015-06-25T17:08:47.190+12:00"></valueInstant>
                </extension>
                <code>
                    <coding>
                        <system value="http://loinc.org"></system>
                        <code value="3141-9"></code>
                    </coding>
                </code>
                <valueString value="observationValue"></valueString>
                <status value="final"></status>
                <reliability value="ok"></reliability>
                <subject>
                    <reference value="Patient/INGE6TSFFVAUCMJQGJAHA5LQOBSXI"></reference>
                </subject>
            </Observation>
        </resource>
    </entry>
</Bundle>
``` 

Please note the presence of entry links like:
```xml
    <entry>
        <link>
            <relation value="orionhealth.edit"></relation>
            <url value="Observation"></url>
        </link>
```

When I perform the same query from hapi-fhir `GenericClient` I get a `DataFormatException` (see the stack trace below).

I suspect that the problem comes from the client that expects a `ca.uhn.fhir.model.api.Bundle` when executing a `IQuery`, `ca.uhn.fhir.model.api.Bundle` has a list of `ca.uhn.fhir.model.api.BundleEntry` but unfortunately a `ca.uhn.fhir.model.api.BundleEntry` does not have links.

I guess the fix would be to have a DTSU2 rest client that sends and receives DSTU2 bundle. 

Exception stack trace:
```
ca.uhn.fhir.parser.DataFormatException: DataFormatException at [[row,col {unknown-source}]: [1,467]]: Unexpected element in entry: link
	at ca.uhn.fhir.parser.XmlParser.doXmlLoop(XmlParser.java:211)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:987)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:982)
	at ca.uhn.fhir.rest.client.GenericClient$BundleResponseHandler.invokeClient(GenericClient.java:617)
	at ca.uhn.fhir.rest.client.GenericClient$BundleResponseHandler.invokeClient(GenericClient.java:601)
	at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:318)
	at ca.uhn.fhir.rest.client.GenericClient$BaseClientExecutable.invoke(GenericClient.java:579)
	at ca.uhn.fhir.rest.client.GenericClient$SearchInternal.execute(GenericClient.java:1405)
	at ca.uhn.fhir.rest.client.GenericClient$SearchInternal.execute(GenericClient.java:1348)
	at com.orchestral.data.fhir.stepdefs.BaseStepDefs.executeQuery(BaseStepDefs.java:130)
	at com.orchestral.data.fhir.stepdefs.ReadTransactionStepDefs.I_query_for_all_Heart_Rate_Observations(ReadTransactionStepDefs.java:155)
	at ✽.When I query for all Heart Rate Observations(com/orchestral/data/fhir/features/readTransaction.dstu1.feature:35)
Caused by: ca.uhn.fhir.parser.DataFormatException: Unexpected element in entry: link
	at ca.uhn.fhir.parser.ParserState$BundleEntryState.enteringNewElement(ParserState.java:1056)
	at ca.uhn.fhir.parser.ParserState.enteringNewElement(ParserState.java:105)
	at ca.uhn.fhir.parser.XmlParser.doXmlLoop(XmlParser.java:182)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:987)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:982)
	at ca.uhn.fhir.rest.client.GenericClient$BundleResponseHandler.invokeClient(GenericClient.java:617)
	at ca.uhn.fhir.rest.client.GenericClient$BundleResponseHandler.invokeClient(GenericClient.java:601)
	at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:318)
	at ca.uhn.fhir.rest.client.GenericClient$BaseClientExecutable.invoke(GenericClient.java:579)
	at ca.uhn.fhir.rest.client.GenericClient$SearchInternal.execute(GenericClient.java:1405)
	at ca.uhn.fhir.rest.client.GenericClient$SearchInternal.execute(GenericClient.java:1348)
```

**Comment by jamesagnew** [comment]
Hi Joel,

The solution here would definitely be to use a DSTU2 Bundle resource for your search result. You need to instruct the client specifically to return this, like so:
```java
ca.uhn.fhir.model.dstu2.resource.Bundle response = client.search()
			.forResource("Observation")
			.where(Patient.NAME.matches().value("FOO"))
			.returnBundle(ca.uhn.fhir.model.dstu2.resource.Bundle.class)
			.execute();
```

Ps, hope you don't mind, I turned your example Bundle into a set of unit tests just to make sure we could handle the link relations you are using.

**Comment by joel-costigliola** [comment]
Great ! :)
May I suggest to add a quick note to the documentation in the [DSTU2 section](http://jamesagnew.github.io/hapi-fhir/doc_dstu2.html) ? 
I'm saying that as I'm not the only in my team that did not find the proper way to return DST2 bundles from queries.

**Comment by joel-costigliola** [comment]
We are using hapi-fhir-base 1.0 and it does not seem to provide this method, is that normal ? 
 see http://search.maven.org/remotecontent?filepath=ca/uhn/hapi/fhir/hapi-fhir-base/1.0/hapi-fhir-base-1.0-sources.jar.

Weird thing is that the `returnBundle` has been added in https://github.com/jamesagnew/hapi-fhir/commit/b42737262b2bbf6a233f01ffd4d7165f93296fc4#diff-d78e10d0d5753cac2e71ef306301dbe1 on the 20th of April but is not present in the 1.0 version released in May.

**Comment by joel-costigliola** [comment]
I have built locally hapi-fhir 1.1-SNAPSHOT and was able to run my test/scenario.

@jamesagnew  Do you plan to do a new release soon ?

**Comment by joel-costigliola** [comment]
@jamesagnew any comments on this issue ? I know I can build and publish in my company a version of hapi-fhir version fixing this problem but I would really prefer to avoid that if possible.

**Comment by jamesagnew** [comment]
Hi Joel, sorry for the slow reply, it's Canada Day week up here, so a lot
of us are away. :)

Yup, we're planning on tagging 1.1 this week.

James

sent from my phone.

**Comment by joel-costigliola** [comment]
excellent ! :+1:
