### ISSUE TITLE
jpaserver - Exception when paging a search with _includes reaches PreFetchThreshold

### ISSUE THREAD

**Issue by gematik-fue** [jamesagnew/hapi-fhir#1924]
**Describe the bug**
When the system is configured to use DatabaseBackedPagingProvider, pagination may fail when a search conatins additional resources within first PrefetchThreshhold iteration but has enough results  to require a SearchContinuationTask to complete

When and if this bug triggers, depends on a few factors
- configured page size
- configured max page size
- available resources
- DaoConfig.mySearchPreFetchThresholds

**To Reproduce**
1. Go to 'http://hapi.fhir.org/baseR4/Patient/UMA-2113340-2/$everything' (or POST [Patient-DSTU3 everything-UMA-2113340-2 transaction bundle](https://github.com/jamesagnew/hapi-fhir/files/4785835/Patient-everything-UMA-2113340-2.zip) to your own jpaserver)
2. progress through result pages by clicking on `next` links
3. See error (expected to pop up on reaching `_getpageoffset=160`)

**Expected behavior**
The internal search task of SearchCoordinatorSvcImpl should complete successfully

**Screenshots**
```
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at ca.uhn.fhir.jpa.dao.SearchBuilder$QueryIterator.fetchNext(SearchBuilder.java:1048)
	at ca.uhn.fhir.jpa.dao.SearchBuilder$QueryIterator.hasNext(SearchBuilder.java:1173)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchTask.doSearch(SearchCoordinatorSvcImpl.java:1089)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchTask.access$2200(SearchCoordinatorSvcImpl.java:614)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchTask$3.doInTransactionWithoutResult(SearchCoordinatorSvcImpl.java:892)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchTask.call(SearchCoordinatorSvcImpl.java:889)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchContinuationTask.call(SearchCoordinatorSvcImpl.java:1163)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl$SearchContinuationTask.call(SearchCoordinatorSvcImpl.java:1130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Environment :**
- HAPI 5.0.0, 5.02, 4.2.0
- OpenJDK8  (Ubuntu 16.04), whatever `maven jetty:run` in hapi-fhir-jpaserver-starter uses
- MySQL5.7, H2

**Additional context**
Example data from our test case
[Patient-everything-UMA-2113340-2.zip](https://github.com/jamesagnew/hapi-fhir/files/4785835/Patient-everything-UMA-2113340-2.zip)

**Comment by gematik-fue** [comment]
My naive attempt to fix this 
https://github.com/jamesagnew/hapi-fhir/commit/4f4af16560f50d3b82476aa4b351492b7dcce248
