### ISSUE TITLE
No narrative available - Error: The value specified for property 'http://xml.org/sax/properties/lexical-handler' cannot be casted to org.xml.sax.ext.LexicalHandler

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#193]
James,
when I make the following call I get  in all the XML resoponses:
Request:
GET http://localhost:9988/fhir/base/metadata

Result:
{
  "resourceType": "Conformance",
  "text": {
    "status": "empty",
    "div": "<div>No narrative available - Error: The value specified for property 'http://xml.org/sax/properties/lexical-handler' cannot be casted to org.xml.sax.ext.LexicalHandler.</div>"
  },
  "contained": [
    {
      "resourceType": "OperationDefinition",
      "id": "1",
      "text": {
        "status": "empty",
        "div": "<div>No narrative available - Error: The value specified for property 'http://xml.org/sax/properties/lexical-handler' cannot be casted to org.xml.sax.ext.LexicalHandler.</div>"
      },
      "status": "active",
      "idempotent": true,
      "code": "$validate",
      "type": [
        "AllergyIntolerance"
      ],
      "instance": true,
      "parameter": [
        {
          "name": "resource",
          "use": "in",
          "min": 0,
          "max": "1"
        },
        {
          "name": "mode",
          "use": "in",
          "min": 0,
          "max": "1"
        },
        {
          "name": "profile",
          "use": "in",
          "min": 0,
          "max": "1"
        }
      ]
    },
...........

The stack trace shows:
2015-07-02 12:09:25,732 ERROR [Jetty Transport Thread [0.0.0.0:9988]-5] BaseThymeleafNarrativeGenerator - Failed to generate narrative
org.xml.sax.SAXNotSupportedException: The value specified for property 'http://xml.org/sax/properties/lexical-handler' cannot be casted to org.xml.sax.ext.LexicalHandler.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.setProperty(AbstractSAXParser.java:1879)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.setProperty(SAXParserImpl.java:518)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.setProperty(SAXParserImpl.java:278)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:203)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:134)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:116)
	at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:278)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:924)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:898)
	at ca.uhn.fhir.narrative.BaseThymeleafNarrativeGenerator.generateNarrative(BaseThymeleafNarrativeGenerator.java:143)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:508)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:665)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:773)
	at ca.uhn.fhir.parser.JsonParser.encodeChildElementToStreamWriter(JsonParser.java:456)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementChildrenToStreamWriter(JsonParser.java:521)
	at ca.uhn.fhir.parser.JsonParser.encodeCompositeElementToStreamWriter(JsonParser.java:665)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:773)
	at ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter(JsonParser.java:691)
	at ca.uhn.fhir.parser.JsonParser.doEncodeResourceToWriter(JsonParser.java:784)
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:260)
	at ca.uhn.fhir.rest.server.RestfulServerUtils.streamResponseAsResource(RestfulServerUtils.java:432)
	at ca.uhn.fhir.rest.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:392)
	at ca.uhn.fhir.rest.method.ConformanceMethodBinding.invokeServer(ConformanceMethodBinding.java:38)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:700)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:149)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at com.soa.transport.jetty.MixedContextHandler.doHandle(MixedContextHandler.java:403)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:67)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:367)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)

and when you go to line 143 of ca.uhn.fhir.narrative.BaseThymeleafNarrativeGenerator.generateNarrative you see the following:

try {
			Context context = new Context();
			context.setVariable("resource", theResource);
			context.setVariable("fhirVersion", myFhirContext.getVersion().getVersion().name());

			String result = myProfileTemplateEngine.process(name, context); (this is line 143)

Notice this line directly above it:
ontext.setVariable("fhirVersion", myFhirContext.**getVersion().getVersion()**.name());

is this correct?

**Comment by pogo61** [comment]
James,
you can close this...turned out to be an issue with the bundle classpath.

PS I have now been able to make the server work in our container (with the help of Bill and another engineer at Akana) using the example, read-only, resource providers.
