### ISSUE TITLE
Failed to call access method

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#195]
Hi James,
it looks like I've got issues with any JPA actions on any resource.

I get this error for a Patient create (I can send the whole log file, including DEBUG on the server startup, if you want):
2015-07-06 13:41:03,443 ERROR [Jetty Transport Thread [0.0.0.0:9988]-4] BaseOutcomeReturningMethodBinding - Internal error during method invocation
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method
	at ca.uhn.fhir.rest.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:262)
	at ca.uhn.fhir.rest.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154)
	at ca.uhn.fhir.rest.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:35)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:700)
	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at com.soa.transport.jetty.MixedContextHandler.doHandle(MixedContextHandler.java:403)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:67)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:367)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at ca.uhn.fhir.rest.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:257)
	... 31 more
Caused by: java.lang.NullPointerException
	at ca.uhn.fhir.jpa.dao.BaseFhirDao.updateEntity(BaseFhirDao.java:1091)
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.doCreate(BaseFhirResourceDao.java:1136)
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.create(BaseFhirResourceDao.java:833)
	at ca.uhn.fhir.jpa.dao.BaseFhirResourceDao.create(BaseFhirResourceDao.java:813)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at $Proxy76.create(Unknown Source)
	at ca.uhn.fhir.jpa.provider.JpaResourceProviderDstu2.create(JpaResourceProviderDstu2.java:72)
	... 36 more

Any pointers on what I'm missing?

**Comment by jamesagnew** [comment]
Hi Paul,

What's happening at the line where the NPE is happening? e.g.
ca.uhn.fhir.jpa.dao.BaseFhirDao.updateEntity(BaseFhirDao.java:1091)

In the current trunk
<https://github.com/jamesagnew/hapi-fhir/blob/61d4887f77c3880d0567ff5f38b240ebbaad4334/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseFhirDao.java#L1091>
that doesn't line up to anything where an NPE could be happening. On your
branch
<https://github.com/pogo61/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseFhirDao.java#L1091>
it looks like myEntityManager is null, which seems to suggest that Spring
isn't loading properly..

Cheers,
James

**Comment by pogo61** [comment]
Thanks James, that’s exactly what’s happening.

where is the spring  configs for the entity manager, is it the hapi-fhir-server-database-config.xml file

PP

**Comment by jamesagnew** [comment]
Hi Paul,

In a bunch of our examples that's where it is found, yup. If that field is
not getting set you might want to make sure you have
'<context:annotation-config />' in all of the XML files you are using to
set up spring.

Cheers,
James

**Comment by pogo61** [comment]
Thanks James. 
It might be that, and class path issues with the bundle(s)

**Comment by seanmcilvenna** [comment]
Did adding <context:annotation-config /> to the spring setup fix this problem for you? We are encountering the same problem... But, not sure of the solution. And I am not a very good Java developer :)

**Comment by jamesagnew** [comment]
I'd recommend trying with one of our sample projects (none of which use the
XML style config). They are known to work correctly.

sent from my phone.

**Comment by mmreith** [comment]
Hey,

i have the same problems, but in another context...
Hapi FHIR Example 3.7.0 or http://fhirtest.uhn.ca/baseDstu3

Trying to post a bundle with one codesystem...

<Bundle xmlns="http://hl7.org/fhir">
<type value="transaction"/>
<entry>
<resource>
<CodeSystem xmlns="http://hl7.org/fhir">
<url value= "https://fhir.kbv.de/CodeSystem/74_CS_AW_Satzart"/>
<version value="1.10"/>
<name value="74_CS_AW_Satzart"/>
<status value="active"/>
<experimental value="false"/>
<date value="2018-10-05"/>
<publisher value="Kassenaerztliche Bundesvereinigung"/>
<contact>
<telecom>
<system value="url"/>
<value value="http://www.kbv.de"/>
</telecom>
</contact>
<description value="Satzarten"/>
<copyright value="Kassenaerztliche Bundesvereinigung"/>
<caseSensitive value="true"/>
<content value="complete"/>
<concept>
<code value="0101"/>
<display value="Ambulante Behandlung"/>
</concept>
<concept>
<code value="0102"/>
<display value="Ueberweisung"/>
</concept>
<concept>
<code value="0102"/>
<display value="Ueberweisung"/>
</concept>
<concept>
<code value="0103"/>
<display value="Belegaerztliche Behandlung"/>
</concept>
<concept>
<code value="0104"/>
<display value="Notfalldienst/Vetretung/Notfall"/>
</concept>
<concept>
<code value="0109"/>
<display value="Kuraerztliche Behandlung"/>
</concept>
<concept>
<code value="sad1"/>
<display value="SADT-Ambulante Behandlung"/>
</concept>
<concept>
<code value="sad2"/>
<display value="SADT-Ueberweisung"/>
</concept>
<concept>
<code value="sad3"/>
<display value="SADT-Belegaerztliche Behandlung"/>
</concept>
</CodeSystem>
</resource>
<request>
<method value="POST"/>
</request>
</entry>
</Bundle>


The $validate operation seems to mark them ok, but while pasting them i get this error:

Error: HTTP 500 Server Error: Failed to call access method: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into TRM_CONCEPT (CODE, CODESYSTEM_PID, DISPLAY, INDEX_STATUS, PARENT_PIDS, CODE_SEQUENCE, CONCEPT_UPDATED, PID) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [idx_concept_cs_code]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch

**Comment by mmreith** [comment]
Hey,

i have the same problems in another context

Hapi FHIR 3.7.0 or http://fhirtest.uhn.ca/baseDstu3

while posting this code snippet:

```
<Bundle xmlns="http://hl7.org/fhir">
<type value="transaction"/>
<entry>
<resource>
<CodeSystem xmlns="http://hl7.org/fhir">
<url value= "https://fhir.kbv.de/CodeSystem/74_CS_AW_Satzart"/>
<version value="1.10"/>
<name value="74_CS_AW_Satzart"/>
<status value="active"/>
<experimental value="false"/>
<date value="2018-10-05"/>
<publisher value="Kassenaerztliche Bundesvereinigung"/>
<contact>
<telecom>
<system value="url"/>
<value value="http://www.kbv.de"/>
</telecom>
</contact>
<description value="Satzarten"/>
<copyright value="Kassenaerztliche Bundesvereinigung"/>
<caseSensitive value="true"/>
<content value="complete"/>
<concept>
<code value="0101"/>
<display value="Ambulante Behandlung"/>
</concept>
<concept>
<code value="0102"/>
<display value="Ueberweisung"/>
</concept>
<concept>
<code value="0102"/>
<display value="Ueberweisung"/>
</concept>
<concept>
<code value="0103"/>
<display value="Belegaerztliche Behandlung"/>
</concept>
<concept>
<code value="0104"/>
<display value="Notfalldienst/Vetretung/Notfall"/>
</concept>
<concept>
<code value="0109"/>
<display value="Kuraerztliche Behandlung"/>
</concept>
<concept>
<code value="sad1"/>
<display value="SADT-Ambulante Behandlung"/>
</concept>
<concept>
<code value="sad2"/>
<display value="SADT-Ueberweisung"/>
</concept>
<concept>
<code value="sad3"/>
<display value="SADT-Belegaerztliche Behandlung"/>
</concept>
</CodeSystem>
</resource>
<request>
<method value="POST"/>
</request>
</entry>
</Bundle>
```

i get this error:

```
Error: HTTP 500 Server Error: Failed to call access method: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into TRM_CONCEPT (CODE, CODESYSTEM_PID, DISPLAY, INDEX_STATUS, PARENT_PIDS, CODE_SEQUENCE, CONCEPT_UPDATED, PID) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [idx_concept_cs_code]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
```

The $validate check marked this resource... without faults

Is this a issue or did i something wrong?

greetings Max
