### ISSUE TITLE
"Failed to call access method: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0" while validating

### ISSUE THREAD

**Issue by desjob** [jamesagnew/hapi-fhir#2095]
**Describe the bug**
While calling the $validate resource operation, i sometimes get the error below. While other validation issues have been in context of the profile and resource that I am validating, this error means nothing to me and I have no idea how to fix it.

note: this error only occurs a part of the time. I.e. if I repeat the same $validate request 10 times, I will get this error only a few times, and an actual list of resource specific validation issues the rest of the times.

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0"
        }
    ]
}
```

<details>
<summary>Docker logs (click to expand):</summary>
<p>

```
hapi-fhir-jpaserver-start    | 2020-09-21 10:48:51.376 [http-nio-8080-exec-47] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:140] Failure during REST processing
hapi-fhir-jpaserver-start    | ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:250)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:329)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:247)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:384)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:304)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1029)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:363)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1722)
hapi-fhir-jpaserver-start    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
hapi-fhir-jpaserver-start    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
hapi-fhir-jpaserver-start    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
hapi-fhir-jpaserver-start    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
hapi-fhir-jpaserver-start    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
hapi-fhir-jpaserver-start    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
hapi-fhir-jpaserver-start    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
hapi-fhir-jpaserver-start    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
hapi-fhir-jpaserver-start    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
hapi-fhir-jpaserver-start    | 	at java.base/java.lang.Thread.run(Thread.java:834)
hapi-fhir-jpaserver-start    | Caused by: java.lang.reflect.InvocationTargetException: null
hapi-fhir-jpaserver-start    | 	at jdk.internal.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
hapi-fhir-jpaserver-start    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hapi-fhir-jpaserver-start    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245)
hapi-fhir-jpaserver-start    | 	... 30 common frames omitted
hapi-fhir-jpaserver-start    | Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
hapi-fhir-jpaserver-start    | 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
hapi-fhir-jpaserver-start    | 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
hapi-fhir-jpaserver-start    | 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.Objects.checkIndex(Objects.java:372)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.ArrayList.get(ArrayList.java:458)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.dstu3.conformance.ProfileUtilities.updateFromDefinition(ProfileUtilities.java:1186)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.dstu3.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:760)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.dstu3.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:389)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.dstu3.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:518)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.dstu3.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:389)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.support.SnapshotGeneratingValidationSupport.generateSnapshot(SnapshotGeneratingValidationSupport.java:54)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.support.ValidationSupportChain.generateSnapshot(ValidationSupportChain.java:65)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.support.BaseValidationSupportWrapper.generateSnapshot(BaseValidationSupportWrapper.java:93)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.lambda$new$0(VersionSpecificWorkerContextWrapper.java:91)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3670)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2362)
hapi-fhir-jpaserver-start    | 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
hapi-fhir-jpaserver-start    | 	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.fetchResource(VersionSpecificWorkerContextWrapper.java:290)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.VersionSpecificWorkerContextWrapper.fetchRawProfile(VersionSpecificWorkerContextWrapper.java:371)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.fetchAndAddProfile(ValidatorWrapper.java:195)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.ValidatorWrapper.validate(ValidatorWrapper.java:135)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validate(FhirInstanceValidator.java:301)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.doValidate(BaseValidatorBridge.java:22)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.BaseValidatorBridge.validateResource(BaseValidatorBridge.java:45)
hapi-fhir-jpaserver-start    | 	at org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator.validateResource(FhirInstanceValidator.java:30)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.validation.FhirValidator.validateWithResult(FhirValidator.java:221)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.validate(BaseHapiFhirResourceDao.java:1429)
hapi-fhir-jpaserver-start    | 	at jdk.internal.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
hapi-fhir-jpaserver-start    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hapi-fhir-jpaserver-start    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
hapi-fhir-jpaserver-start    | 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hapi-fhir-jpaserver-start    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
hapi-fhir-jpaserver-start    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hapi-fhir-jpaserver-start    | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
hapi-fhir-jpaserver-start    | 	at com.sun.proxy.$Proxy203.validate(Unknown Source)
hapi-fhir-jpaserver-start    | 	at ca.uhn.fhir.jpa.provider.dstu3.JpaResourceProviderDstu3.validate(JpaResourceProviderDstu3.java:196)
hapi-fhir-jpaserver-start    | 	... 34 common frames omitted
hapi-fhir-jpaserver-start    | 2020-09-21 10:48:51.376 [http-nio-8080-exec-47] INFO  fhirtest.access [LoggingInterceptor.java:160] ERROR - GET http://localhost:11100/hapi-fhir-jpaserver/fhir/Patient/2/$validate
```

</p>
</details>

**To Reproduce**
1. run a jpa server with the docker-compose.yml and hapi.properties below
2. use vonkloader to import the https://simplifier.net/nictizstu3-zib2017/$download?filter=Resource project files:
```
vonkloader -file:/home/username/Downloads/nictizstu3-zib2017.zip -parallel:2 -server:http://localhost:11100/hapi-fhir-jpaserver/fhir
```
3. repeatedly validate one of the example patients from the imported simplifier project:
```
curl --location --request GET 'http://localhost:11100/hapi-fhir-jpaserver/fhir/Patient/nl-core-patient-01/$validate'
```

**Expected behavior**
The following response (**note**: this does happen some of the time when repeating the same request)

<details>
<summary>Response (click to expand):</summary>
<p>

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[Patient.telecom[0], Line 1, Col 2069]</td><td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.telecom[1], Line 1, Col 2435]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.gender, Line 1, Col 2549]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.birthDate, Line 1, Col 2841]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.deceased.ofType(boolean), Line 1, Col 2873]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.address[0], Line 1, Col 2882]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.maritalStatus, Line 1, Col 3938]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.multipleBirth.ofType(boolean), Line 1, Col 4105]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.contact[0], Line 1, Col 4114]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">ERROR</td>\n\t\t\t\t<td>[Patient.generalPractitioner[0], Line 1, Col 6726]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"font-weight: bold;\">INFORMATION</td>\n\t\t\t\t<td>[Patient.meta.extension[0], Line 1, Col 158]</td>\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\t<td><pre>Unknown extension http://hapifhir.io/fhir/StructureDefinition/resource-meta-source</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.telecom[0]",
                "Line 1, Col 2069"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.telecom[1]",
                "Line 1, Col 2435"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.gender",
                "Line 1, Col 2549"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.birthDate",
                "Line 1, Col 2841"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.deceased.ofType(boolean)",
                "Line 1, Col 2873"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.address[0]",
                "Line 1, Col 2882"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.maritalStatus",
                "Line 1, Col 3938"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.multipleBirth.ofType(boolean)",
                "Line 1, Col 4105"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.contact[0]",
                "Line 1, Col 4114"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "This element is not allowed by the profile http://fhir.nl/fhir/StructureDefinition/nl-core-patient",
            "location": [
                "Patient.generalPractitioner[0]",
                "Line 1, Col 6726"
            ]
        },
        {
            "severity": "information",
            "code": "processing",
            "diagnostics": "Unknown extension http://hapifhir.io/fhir/StructureDefinition/resource-meta-source",
            "location": [
                "Patient.meta.extension[0]",
                "Line 1, Col 158"
            ]
        }
    ]
}
```

</p>
</details>

**Environment:**

<details>
<summary>**docker-compose.yml** (click to expand):</summary>
<p>

```
version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: docker.io/hapiproject/hapi:v5.0.0
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "11100:8080"
    volumes:
    - ./hapi.properties:/medicore/hapifhir/hapi.properties
    environment:
      JAVA_OPTS: "-Dhapi.properties=/medicore/hapifhir/hapi.properties"
    depends_on:
    - hapi-fhir-mysql
  hapi-fhir-mysql:
    image: mysql:8.0
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
```

</p>
</details>

<details>
<summary>**hapi.properties** (click to expand):</summary>
<p>

```
# Adjust this to set the version of FHIR supported by this server. See
# FhirVersionEnum for a list of available constants. Example values include
# DSTU2, DSTU3, R4.
fhir_version=DSTU3

# This is the address that the FHIR server will report as its own address.
# If this server will be deployed (for example) to an internet accessible
# server, put the DNS name of that server here.
#
# Note that this is also the address that the hapi-fhir-testpage-overlay
# (the web UI similar to the one at http://hapi.fhir.org) will use to
# connect internally to the FHIR server, so this also needs to be a name
# accessible from the server itself.
server_address=https://hapifhir-acc.mcapp.nl/hapi-fhir-jpaserver/fhir/

enable_index_missing_fields=false
auto_create_placeholder_reference_targets=false
enforce_referential_integrity_on_write=false
enforce_referential_integrity_on_delete=false
default_encoding=JSON
etag_support=ENABLED
reuse_cached_search_results_millis=60000
retain_cached_searches_mins=60
default_page_size=20
max_page_size=200
allow_override_default_search_params=true
allow_contains_searches=true
allow_multiple_delete=true
allow_external_references=true
allow_cascading_deletes=true
allow_placeholder_references=true
expunge_enabled=true
persistence_unit_name=HAPI_PU
logger.name=fhirtest.access
logger.format=Path[${servletPath}] Source[${requestHeader.x-forwarded-for}] Operation[${operationType} ${operationName} ${idOrResourceName}] UA[${requestHeader.user-agent}] Params[${requestParameters}] ResponseEncoding[${responseEncodingNoDefault}]
logger.error_format=ERROR - ${requestVerb} ${requestUrl}
logger.log_exceptions=true
#datasource.driver=org.h2.Driver
#datasource.url=jdbc:h2:file:./target/database/h2
datasource.driver=com.mysql.jdbc.Driver
datasource.url=jdbc:mysql://hapi-fhir-mysql:3306/hapi
datasource.username=admin
datasource.password=admin
server.name=Local Tester
server.id=home
test.port=

###################################################
# Binary Storage (104857600 = 100mb)
###################################################
max_binary_size=104857600

###################################################
# Validation
###################################################
# Should all incoming requests be validated
validation.requests.enabled=false
# Should outgoing responses be validated
validation.responses.enabled=false

###################################################
# Search Features
###################################################
filter_search.enabled=true
graphql.enabled=true

###################################################
# Supported Resources
###################################################
# Enable the following property if you want to customize the
# list of resources that is supported by the server (i.e. to
# disable specific resources)
#supported_resource_types=Patient,Observation,Encounter

###################################################
# Database Settings
###################################################
#hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.search.model_mapping=ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
hibernate.format_sql=false
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update
hibernate.jdbc.batch_size=20
hibernate.cache.use_query_cache=false
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_structured_entries=false
hibernate.cache.use_minimal_puts=false
hibernate.search.default.directory_provider=filesystem
hibernate.search.default.indexBase=target/lucenefiles
hibernate.search.lucene_version=LUCENE_CURRENT
tester.config.refuse_to_fetch_third_party_urls=false

##################################################
# ElasticSearch
# Note that using ElasticSearch is disabled by
# default and the server will use Lucene instead.
##################################################
elasticsearch.enabled=false
elasticsearch.rest_url=http://localhost:9200
elasticsearch.username=SomeUsername
elasticsearch.password=SomePassword
elasticsearch.required_index_status=YELLOW
elasticsearch.schema_management_strategy=CREATE
# Immediately refresh indexes after every write. This is very bad for
# performance, but can be helpful for testing.
elasticsearch.debug.refresh_after_write=false
elasticsearch.debug.pretty_print_json_log=false


##################################################
# Binary Storage Operations
##################################################
binary_storage.enabled=true

##################################################
# Bulk Data Specification
##################################################
bulk.export.enabled=true

##################################################
# CORS Settings
##################################################
cors.enabled=true
cors.allowCredentials=true
# Supports multiple, comma separated allowed origin entries
# cors.allowed_origin=http://localhost:8080,https://localhost:8080,https://fhirtest.uhn.ca
cors.allow_origin=*

##################################################
# Allowed Bundle Types for persistence (defaults are: COLLECTION,DOCUMENT,MESSAGE)
##################################################
#allowed_bundle_types=COLLECTION,DOCUMENT,MESSAGE,TRANSACTION,TRANSACTIONRESPONSE,BATCH,BATCHRESPONSE,HISTORY,SEARCHSET

##################################################
# Subscriptions
##################################################

# Enable REST Hook Subscription Channel
subscription.resthook.enabled=false

# Enable Email Subscription Channel
subscription.email.enabled=false
email.enabled=false
email.from=some@test.com
email.host=
email.port=0
email.username=
email.password=

# Enable Websocket Subscription Channel
subscription.websocket.enabled=false

###################################################
# Partitioning And Multitenancy
###################################################
partitioning.multitenancy.enabled=false

```

</p>
</details>

**Comment by desjob** [comment]
I can no longer reproduce this issue on the current hapiproject/hapi:latest tag.
It would be great if the current :latest tag could be tagged with a new release tag on docker hub so that I can start deploying this fix :)

Thanks for the great work on this project!
