### ISSUE TITLE
autoCreatePlaceholderReferenceTargets true breaks multi-tenancy

### ISSUE THREAD

**Issue by jtheory** [jamesagnew/hapi-fhir#2209]
**Describe the bug**
Creating a resource that refers to other resources that don't yet exist fails, if multi-tenancy is enabled, and autoCreatePlaceholderReferenceTargets is true.

There are two workarounds:
* set this config value to false (default, though in the jpaserver-starter it defaults to true)
* avoid any references that don't exist

**To Reproduce**
1. Run the jpaserver-starter project with partitioning enabled
2. Create a resource with a reference that doesn't exist. This one works (refers to patient "example") http://hl7.org/fhir/condition-example.json.html

**Expected behavior**
The placeholder resource (the patient, in this case) is created

**Actual behavior**
```
hapi-fhir-server              | 2020-12-01 11:56:54.158 [http-nio-8080-exec-2] INFO  fhirtest.access [LoggingInterceptor.java:160] ERROR - POST http://localhost:8080/fhir/TENANT_A/Condition
hapi-fhir-server              | 2020-12-01 12:06:01.754 [http-nio-8080-exec-3] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:140] Failure during REST processing
hapi-fhir-server              | ca.uhn.fhir.rest.server.exceptions.InternalErrorException: No interceptor provided a value for pointcut: STORAGE_PARTITION_IDENTIFY_READ
hapi-fhir-server              |         at ca.uhn.fhir.jpa.partition.RequestPartitionHelperSvc.validatePartition(RequestPartitionHelperSvc.java:193)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.partition.RequestPartitionHelperSvc.determineReadPartitionForRequest(RequestPartitionHelperSvc.java:105)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doUpdate(BaseHapiFhirResourceDao.java:1449)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.lambda$update$12(BaseHapiFhirResourceDao.java:1414)
hapi-fhir-server              |         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:65)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1414)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1394)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1389)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.update(BaseHapiFhirResourceDao.java:1374)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hapi-fhir-server              |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
hapi-fhir-server              |         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
hapi-fhir-server              |         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hapi-fhir-server              |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
hapi-fhir-server              |         at com.sun.proxy.$Proxy234.update(Unknown Source)

hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.index.DaoResourceLinkResolver.createPlaceholderTargetIfConfiguredToDoSo(DaoResourceLinkResolver.java:131)

hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.index.DaoResourceLinkResolver.findTargetResource(DaoResourceLinkResolver.java:75)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.resolveTargetAndCreateResourceLinkOrReturnNull(SearchParamExtractorService.java:331)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractResourceLinks(SearchParamExtractorService.java:293)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractResourceLinks(SearchParamExtractorService.java:185)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.searchparam.extractor.SearchParamExtractorService.extractFromResource(SearchParamExtractorService.java:100)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.index.SearchParamWithInlineReferencesExtractor.populateFromResource(SearchParamWithInlineReferencesExtractor.java:107)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.updateEntity(BaseHapiFhirDao.java:1047)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doCreateForPostOrPut(BaseHapiFhirResourceDao.java:319)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doCreateForPost(BaseHapiFhirResourceDao.java:247)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.lambda$create$0(BaseHapiFhirResourceDao.java:219)
hapi-fhir-server              |         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:65)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.tx.HapiTransactionService.execute(HapiTransactionService.java:56)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:219)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:204)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
hapi-fhir-server              |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hapi-fhir-server              |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
hapi-fhir-server              |         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
hapi-fhir-server              |         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
hapi-fhir-server              |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
hapi-fhir-server              |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
hapi-fhir-server              |         at com.sun.proxy.$Proxy227.create(Unknown Source)
hapi-fhir-server              |         at ca.uhn.fhir.jpa.provider.dstu3.JpaResourceProviderDstu3.create(JpaResourceProviderDstu3.java:74)
hapi-fhir-server              |         ...
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245)
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.method.BaseOutcomeReturningMethodBinding.invokeServer(BaseOutcomeReturningMethodBinding.java:154)
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.method.CreateMethodBinding.invokeServer(CreateMethodBinding.java:41)
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1052)
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:377)
hapi-fhir-server              |         at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1749)
hapi-fhir-server              |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
hapi-fhir-server              |         ... tomcat & spring boot stuff
```
I separated out the important line — the call to make the placeholder object doesn't pass along the request info, so the partition can't be checked.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2.0, jpaserver-starter
 - OS: Ubuntu

**Comment by jtheory** [comment]
This isn't a blocker for anything I'm working on, just wanted to log it since I've already chased it down.

**Comment by jamesagnew** [comment]
Thanks for reporting with that that detail! I was able to reproduce the issue and it was an easy fix.
