### ISSUE TITLE
NoSuchMethodError: org.apache.commons.lang3.Validate.inclusiveBetween

### ISSUE THREAD

**Issue by pperliti** [jamesagnew/hapi-fhir#394]
Hi,
I'm using Android build of FHIR library (hapi-fhir-android v1.4) within an app I developed some months ago. Everything works fine but on some versions of Xiaomi I'm gettting this error:

java.lang.NoSuchMethodError: org.apache.commons.lang3.Validate.inclusiveBetween
at ca.uhn.fhir.context.BaseRuntimeDeclaredChildDefinition.<init>(BaseRuntimeDeclaredChildDefinition.java:49)
at ca.uhn.fhir.context.BaseRuntimeChildDatatypeDefinition.<init>(BaseRuntimeChildDatatypeDefinition.java:43)
at ca.uhn.fhir.context.RuntimeChildPrimitiveDatatypeDefinition.<init>(RuntimeChildPrimitiveDatatypeDefinition.java:35)
at ca.uhn.fhir.context.ModelScanner.scanCompositeElementForChildren(ModelScanner.java:630)
at ca.uhn.fhir.context.ModelScanner.scanCompositeElementForChildren(ModelScanner.java:399)
at ca.uhn.fhir.context.ModelScanner.scanCompositeDatatype(ModelScanner.java:374)
at ca.uhn.fhir.context.ModelScanner.scan(ModelScanner.java:321)
at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:202)
at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:113)
at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:431)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:140)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:113)
at ca.uhn.fhir.context.FhirContext.forDstu2(FhirContext.java:507)

Another one is:

java.lang.NoSuchMethodError: No static method inclusiveBetween(JJJLjava/lang/String;)V in class Lorg/apache/commons/lang3/Validate; or its super classes (declaration of 'org.apache.commons.lang3.Validate' appears in /system/framework/framework.jar:classes2.dex)
at ca.uhn.fhir.context.BaseRuntimeDeclaredChildDefinition.<init>(BaseRuntimeDeclaredChildDefinition.java:49)
at ca.uhn.fhir.context.BaseRuntimeChildDatatypeDefinition.<init>(BaseRuntimeChildDatatypeDefinition.java:43)
at ca.uhn.fhir.context.RuntimeChildPrimitiveDatatypeDefinition.<init>(RuntimeChildPrimitiveDatatypeDefinition.java:35)
at ca.uhn.fhir.context.ModelScanner.scanCompositeElementForChildren(ModelScanner.java:630)
at ca.uhn.fhir.context.ModelScanner.scanCompositeElementForChildren(ModelScanner.java:399)
at ca.uhn.fhir.context.ModelScanner.scanCompositeDatatype(ModelScanner.java:374)
at ca.uhn.fhir.context.ModelScanner.scan(ModelScanner.java:321)
at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:202)
at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:113)
at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:431)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:140)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:113)
at ca.uhn.fhir.context.FhirContext.forDstu2(FhirContext.java:507)

The app is shpped with commons-lang3-3.4.jar dependency but seems to me that the Xiaomi custom image of Android already comes with a different version of the same library.
Do you know if there's some workaround to force using the latest version of commons-lang3 (shipped with my app) instead of the one shipped with the OS?

Thanks in advance.

Ciao,
Paolo

**Comment by jamesagnew** [comment]
More discussion here: https://groups.google.com/d/msgid/hapi-fhir/CAMKPDh-iWbSzRrUWf%2BpzMV-fr6oWwdJvkD7ft9G-GbOpbNJk9w%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by jamesagnew** [comment]
I'm going to commit a fix which replaces the method call with something local. If anyone can figure out which version of the library is being used by the phone though that would be useful so that we can add a specific test.

**Comment by pperliti** [comment]
Method inclusiveBetween in class Validate is present since version 3.0
https://commons.apache.org/proper/commons-lang/javadocs/api-3.0/org/apache/commons/lang3/Validate.html#inclusiveBetween(T,%20T,%20java.lang.Comparable)

Smartphones with this issue are both Xiaomi or Lenovo (from Android 4.4. to Android 6.0).

Logs do not reveal anything else...

![1](https://cloud.githubusercontent.com/assets/1265443/16376983/b90117b0-3c63-11e6-9b0b-157d4b90ebea.png)
![2](https://cloud.githubusercontent.com/assets/1265443/16376984/bbb7e484-3c63-11e6-81d5-7e5f5c999063.png)
![3](https://cloud.githubusercontent.com/assets/1265443/16376986/bd31ab4c-3c63-11e6-8034-97cf46c9b111.png)

We'll try your fix ASAP.

**Comment by jamesagnew** [comment]
FWIW the specific `inclusiveBetween` method we were calling was the one that takes `long` as its paramrter type, and that one was added in commons-lang3 3.3.... So I guess the Xiaomi phone might have a version of CL3 as new as 3.2
