### ISSUE TITLE
DateParam parsing failing on date with minutes but no seconds  (2.0)

### ISSUE THREAD

**Issue by XcrigX** [jamesagnew/hapi-fhir#462]
Not a huge problem, but the handling of date parsing for ca.uhn.fhir.rest.param.DateParam does not seem to be inline with the FHIR specification. 
From the FHIR spec it appears a date string value with precision only to minutes should be acceptable in a search, but HAPI (2.0) is failing unless seconds are included as well. 

http://hl7.org/fhir/2016Sep/search.html#date

A simple test for this:
`new DateParam(ParamPrefixEnum.LESSTHAN_OR_EQUALS, "2016-09-06T09:05");`

Yields this exception: 
`ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "2016-09-06T09:05"
    at ca.uhn.fhir.model.primitive.BaseDateTimeDt.throwBadDateFormat(BaseDateTimeDt.java:465)
    at ca.uhn.fhir.model.primitive.BaseDateTimeDt.validateLengthIsAtLeast(BaseDateTimeDt.java:526)
    at ca.uhn.fhir.model.primitive.BaseDateTimeDt.parse(BaseDateTimeDt.java:289)
    at ca.uhn.fhir.model.primitive.BaseDateTimeDt.parse(BaseDateTimeDt.java:39)
    at ca.uhn.fhir.model.api.BasePrimitive.setValueAsString(BasePrimitive.java:112)
    at ca.uhn.fhir.model.primitive.BaseDateTimeDt.setValueAsString(BaseDateTimeDt.java:461)
    at ca.uhn.fhir.rest.param.DateParam.setValueAsString(DateParam.java:263)
    at ca.uhn.fhir.rest.param.DateParam.<init>(DateParam.java:94)
`

**Comment by kwboone** [comment]
We have a similar problem.  The format listed in bold below is reporting an error for us as well.

According to the FHIR Specification:

> _Any degree of precision can be provided, but it SHALL be populated from the left (e.g. can't specify a month without a year), except that the minutes SHALL be present if an hour is present, and you SHOULD provide a time zone if the time part is present._

HAPI server currently allows following pattern:
2011-03-06T12:15:22.000+05:30
2011-03-06T12:15:22.000
2011-03-06T12:15:22
2011-03-06
2011-03
2011

HAPI server currently does not allows following pattern:
**2011-03-06T12:15**
2011-03-06T12

**Comment by jamesagnew** [comment]
This was fixed in #655. Can you please try it with HAPI FHIR 2.5?

**Comment by XcrigX** [comment]
Keith, my reading is that hours-only precision is not allowed in search, but hours and minutes is. So your second value should not work, as per the spec. 

And just to note, there is a distinction between what is allowed in SEARCH and what is allowed in the DateTime datatype. The Datetime datatype requires seconds to be present if hours and minutes is present.

**Comment by XcrigX** [comment]
Confirmed fixed. Sorry for the delay in closing.
