### ISSUE TITLE
HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by rqg0717** [jamesagnew/hapi-fhir#492]
Dear all,

I keep getting "HTTP 500 Internal Server Error" when I try to post the following bundle:
```
<Bundle xmlns="http://hl7.org/fhir">
   <type value="transaction"></type>
   <entry>
      <fullUrl value="urn:uuid:7ea9931e-3750-401a-a670-42613922668b"></fullUrl>
      <resource>
         <Patient xmlns="http://hl7.org/fhir">
            <language value="ENGL"></language>
            <identifier>
               <system value="http://www.gim.net/fhir/patients"></system>
               <value value="54e7353a-1c46-4f7e-83ce-380ce0348031"></value>
            </identifier>
            <identifier>
               <system value="https://www.modahealth.com/"></system>
               <value value="ABCDILBXYYY"></value>
            </identifier>
            <name>
               <family value="Ren"></family>
               <given value="James"></given>
               <given value="J"></given>
            </name>
            <telecom>
               <system value="phone"></system>
               <value value="(215) 396-6496"></value>
               <use value="home"></use>
            </telecom>
            <telecom>
               <system value="phone"></system>
               <value value="(484) 889-1827"></value>
               <use value="work"></use>
            </telecom>
            <gender value="female"></gender>
            <birthDate value="1980-01-01"></birthDate>
            <deceasedBoolean value="false"></deceasedBoolean>
            <address>
               <line value="123 Main St."></line>
               <city value="Philadelphia"></city>
               <state value="PA"></state>
               <postalCode value="19122"></postalCode>
            </address>
            <maritalStatus>
               <coding>
                  <system value="http://hl7.org/fhir/v3/MaritalStatus"></system>
                  <code value="M"></code>
               </coding>
            </maritalStatus>
         </Patient>
      </resource>
      <request>
         <method value="POST"></method>
         <url value="Patient"></url>
         <ifNoneExist value="Patient?identifier=https://www.modahealth.com/|ABCDILBXYYY"></ifNoneExist>
      </request>
   </entry>
   <entry>
      <resource>
         <Observation xmlns="http://hl7.org/fhir">
            <status value="final"></status>
            <code>
               <coding>
                  <system value="http://loinc.org"></system>
                  <code value="789-8"></code>
                  <display value="Erythrocytes [#/volume] in Blood by Automated count"></display>
               </coding>
            </code>
            <subject>
               <reference value="urn:uuid:7ea9931e-3750-401a-a670-42613922668b"></reference>
            </subject>
            <valueQuantity>
               <value value="4.12"></value>
               <unit value="10 trillion/L"></unit>
               <system value="http://unitsofmeasure.org"></system>
               <code value="10*12/L"></code>
            </valueQuantity>
         </Observation>
      </resource>
      <request>
         <method value="POST"></method>
         <url value="Observation"></url>
      </request>
   </entry>
   <entry>
      <resource>
         <Coverage xmlns="http://hl7.org/fhir">
            <issuer>
               <reference value="Organization/1"></reference>
            </issuer>
            <period>
               <start value="2014-01-01T00:00:00"></start>
               <end value="2199-12-31T00:00:00"></end>
            </period>
            <identifier>
               <system value="http://definitions.uslegal.com/h/health-insurance-claim-number-hicn"></system>
               <value value="123456789A"></value>
            </identifier>
            <group value="88888888"></group>
            <plan value="888888880008"></plan>
            <subscriber>
               <reference value="Patient/1490639"></reference>
            </subscriber>
         </Coverage>
      </resource>
      <request>
         <method value="POST"></method>
         <url value="Coverage"></url>
      </request>
   </entry>
</Bundle>
```

The server side error:
```
2016-11-09 16:49:19.724 [http-nio-8084-exec-17] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor [ExceptionHandlingInterceptor.java:128] Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method
	at ca.uhn.fhir.rest.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:263)
	at ca.uhn.fhir.rest.method.TransactionMethodBinding.invokeServer(TransactionMethodBinding.java:133)
	at ca.uhn.fhir.rest.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:306)
	at ca.uhn.fhir.rest.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:257)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:665)
	at ca.uhn.fhir.rest.server.RestfulServer.doPost(RestfulServer.java:1225)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1197)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	at org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at ca.uhn.fhir.rest.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:258)
	... 35 common frames omitted
Caused by: java.lang.NoSuchMethodError: ca.uhn.fhir.rest.method.MethodUtil.parseQueryParams(Lca/uhn/fhir/context/RuntimeSearchParam;Ljava/lang/String;Ljava/util/List;)Lca/uhn/fhir/model/api/IQueryParameterAnd;
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.translateMatchUrl(BaseHapiFhirDao.java:1715)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.processMatchUrl(BaseHapiFhirDao.java:915)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.doCreate(BaseHapiFhirResourceDao.java:336)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.create(BaseHapiFhirResourceDao.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy331.create(Unknown Source)
	at ca.uhn.fhir.jpa.dao.FhirSystemDaoDstu2.transaction(FhirSystemDaoDstu2.java:386)
	at ca.uhn.fhir.jpa.dao.FhirSystemDaoDstu2.transaction(FhirSystemDaoDstu2.java:268)
	at ca.uhn.fhir.jpa.dao.FhirSystemDaoDstu2.transaction(FhirSystemDaoDstu2.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy355.transaction(Unknown Source)
	at ca.uhn.fhir.jpa.provider.JpaSystemProviderDstu2.transaction(JpaSystemProviderDstu2.java:219)
	... 40 common frames omitted
```

Please let me know if i did something wrong. 

Thank you,
Ren

**Comment by jamesagnew** [comment]
Hi Ren,

The `NoSuchMethodError` suggests you may have an old version of the library on your classpath. Can you do a clean build of your war project and make sure you only have one copy of hapi-fhir-base in the result?

Cheers,
James

**Comment by rqg0717** [comment]
Thank you for your solution. The problem has been solved.
