### ISSUE TITLE
java.lang.ClassNotFoundException: org.ebaysf.web.cors.CORSFilter

### ISSUE THREAD

**Issue by jayashreeb081767** [jamesagnew/hapi-fhir#496]
/ __/___/ (_)__  ___ ___   __ / /__ / /_/ /___ __  ( _ )
 / _// __/ / / _ \(_-</ -_) / // / -_) __/ __/ // / / _  |
/___/\__/_/_/ .__/___/\__/  \___/\__/\__/\__/\_, /  \___/
           /_/                              /___/
   Configuration: C:\Users\Admin\AppData\Local\Temp\eclipseJettyPlugin.config.hapi_fhir_cli.xml
         Version: 8.1.14.v20131031
         Context: /
            Port: 8080
       Classpath: 
2016-11-14 20:04:55.727:INFO:oejs.Server:jetty-8.1.14.v20131031
2016-11-14 20:04:56.320:WARN:oejs.Holder:
java.lang.ClassNotFoundException: org.ebaysf.web.cors.CORSFilter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:100)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:79)
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:107)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:90)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:768)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedAdapter.start(JettyEmbeddedAdapter.java:67)
	at net.sourceforge.eclipsejetty.starter.common.AbstractJettyLauncherMain.launch(AbstractJettyLauncherMain.java:84)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedLauncherMain.main(JettyEmbeddedLauncherMain.java:42)
2016-11-14 20:04:56.323:WARN:oejuc.AbstractLifeCycle:FAILED CORS Filter: javax.servlet.UnavailableException: org.ebaysf.web.cors.CORSFilter
javax.servlet.UnavailableException: org.ebaysf.web.cors.CORSFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:114)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:90)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:768)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedAdapter.start(JettyEmbeddedAdapter.java:67)
	at net.sourceforge.eclipsejetty.starter.common.AbstractJettyLauncherMain.launch(AbstractJettyLauncherMain.java:84)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedLauncherMain.main(JettyEmbeddedLauncherMain.java:42)
2016-11-14 20:04:56.324:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/,file:/C:/Users/Admin/git/hapi-fhir/hapi-fhir-cli/hapi-fhir-cli-jpaserver/bin/src/main/webapp/},C:\Users\Admin\git\hapi-fhir\hapi-fhir-cli\hapi-fhir-cli-jpaserver\bin\src\main\webapp
javax.servlet.UnavailableException: org.ebaysf.web.cors.CORSFilter
	at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:114)
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:90)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:768)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedAdapter.start(JettyEmbeddedAdapter.java:67)
	at net.sourceforge.eclipsejetty.starter.common.AbstractJettyLauncherMain.launch(AbstractJettyLauncherMain.java:84)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedLauncherMain.main(JettyEmbeddedLauncherMain.java:42)
2016-11-14 20:04:56.396:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
------------------------------------------------
Jetty startup finished in 1.7 s.
Used memory: 3.4 MB of 123.0 MB (1.8 GB maximum)
Console available: type "help".
------------------------------------------------

**Comment by rqg0717** [comment]
I would close this one...
