### ISSUE TITLE
Extension in identifier possibly causes exception for XML output

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#593]
Hello,

I posted following resource to the FHIR server (I use local DSTU3 fhir-jpa-example) 

```xml
			<EligibilityRequest>
				<id value="63025"/>
				<identifier>
					<value value="63025"/>
					<assigner>
						<identifier>
							<value value="1587543978">
								<extension>
									<valueIdentifier>
										<value value="847590324"/>
									</valueIdentifier>
								</extension>
							</value>
						</identifier>
					</assigner>
				</identifier>
				<patient>
					<reference value="Patient/875439-19330706"/>
				</patient>
				<organization>
					<reference value="Organization/123456781"/>
				</organization>
				<insurer>
					<reference value="Organization/123456780"/>
				</insurer>
				<coverage>
					<reference value="Coverage/875439"/>
				</coverage>
				<benefitCategory>
					<extension>
						<valueDate value="2006-01-01"/>
					</extension>
					<coding>
						<code value="D0140"/>
					</coding>
				</benefitCategory>
				<benefitSubCategory>
					<coding>
						<system value="HC"/>
						<code value="D0140"/>
					</coding>
				</benefitSubCategory>
			</EligibilityRequest>
```

Then when I tried to get it as a JSON I got normal result:

```json 
{
  "resourceType": "EligibilityRequest",
  "id": "20",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2017-03-13T07:40:45.102-07:00"
  },
  "identifier": [
    {
      "value": "63025",
      "assigner": {
        "identifier": {
          "value": "1587543978",
          "_value": {
            "extension": [
              {
                "url": null,
                "valueIdentifier": {
                  "value": "847590324"
                }
              }
            ]
          }
        }
      }
    }
  ],
  "patient": {
    "reference": "Patient/16"
  },
  "organization": {
    "reference": "Organization/15"
  },
  "insurer": {
    "reference": "Organization/14"
  },
  "coverage": {
    "reference": "Coverage/19"
  },
  "benefitCategory": {
    "extension": [
      {
        "url": null,
        "valueDate": "2006-01-01"
      }
    ],
    "coding": [
      {
        "code": "D0140"
      }
    ]
  },
  "benefitSubCategory": {
    "coding": [
      {
        "system": "HC",
        "code": "D0140"
      }
    ]
  }
}```

But when I tried to get this rersource as XML I got exception on FHIR server side

```exception
2017-03-13 08:23:38.753 [qtp40177529-57] WARN  ca.uhn.fhir.to.BaseController [BaseController.java:311] Failed to invoke server
ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Encountered IOException when performing GET to URL http://localhost:8083/hapi-fhir-jpaserver-example/baseDstu3/EligibilityRequest/20/_history/1?_format=xml&_pretty=true - jav
a.io.EOFException
        at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:333)
        at ca.uhn.fhir.rest.client.GenericClient.doReadOrVRead(GenericClient.java:192)
        at ca.uhn.fhir.rest.client.GenericClient.vread(GenericClient.java:506)
        at ca.uhn.fhir.to.Controller.actionRead(Controller.java:315)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:247)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at org.apache.http.client.protocol.ResponseContentEncoding$1.create(ResponseContentEncoding.java:67)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:54)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:66)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:721)
        at ca.uhn.fhir.to.BaseController$CaptureInterceptor.interceptResponse(BaseController.java:743)
        at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:243)
        ... 48 common frames omitted
```

**Comment by SRiviere** [comment]
Hi,
You don't have url in your extension definition which is a mandatory value:
[https://www.hl7.org/fhir/extensibility.html#Extension](https://www.hl7.org/fhir/extensibility.html#Extension)

I'm surprised that you don't have error during the Json parsing too.
