### ISSUE TITLE
Crash on some Android versions

### ISSUE THREAD

**Issue by MarcABernard** [jamesagnew/hapi-fhir#722]
I have a weird problem with crashes on specific Android versions, when I call FhirContext.forDstu3().

I've tried adding the dependency like this:

compile 'ca.uhn.hapi.fhir:hapi-fhir-android:2.5:dstu3@jar'

And also by adding the jar files to my libs directory.

Either way, I get the error java.lang.NoClassDefFoundError: ca.uhn.fhir.rest.server.RestfulServer. The weird part is that some devices/emulators work, and some crash with the same stack trace.

6.0.1 Nexus 7 device crashes
6.0 emulator crashes
6.0 LG G3 device OK
7.0 emulator OK
8.0 emulator OK

08-30 12:40:26.253 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336] No pending exception expected: java.lang.NoClassDefFoundError: ca.uhn.fhir.rest.server.RestfulServer
08-30 12:40:26.253 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, java.lang.Object) (DexFile.java:-2)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, java.lang.Object, java.util.List) (DexFile.java:226)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:338)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:324)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:285)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at boolean ca.uhn.fhir.context.FhirVersionEnum.isPresentOnClasspath() (FhirVersionEnum.java:104)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at void ca.uhn.fhir.context.FhirContext.<init>(ca.uhn.fhir.context.FhirVersionEnum, java.util.Collection) (FhirContext.java:152)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at void ca.uhn.fhir.context.FhirContext.<init>(ca.uhn.fhir.context.FhirVersionEnum) (FhirContext.java:145)
08-30 12:40:26.254 17024-17024/com.agfa.eimobility.demo A/art: art/runtime/thread.cc:1336]   at ca.uhn.fhir.context.FhirContext ca.uhn.fhir.context.FhirContext.forDstu3() (FhirContext.java:895)

I'm not sure where to start looking. Any tips to point me in the right direction?

**Comment by jamesagnew** [comment]
Hi @MarcABernard,

There is a sample project [here](https://github.com/hapifhir/hapi-fhir-android-integration-test) that might be of use in figuring out needed dependencies to get this working.

Altenrately, if you are willing to trying out the latest `3.0.0-SNAPSHOT` builds, you will no longer need to use the `dstu3` artifact classifier (ie you would use `compile 'ca.uhn.hapi.fhir:hapi-fhir-android:3.0.0-SNAPSHOT@jar'` and ``compile 'ca.uhn.hapi.fhir:hapi-fhir-structures-dstu3:3.0.0-SNAPSHOT@jar'` instead of `compile 'ca.uhn.hapi.fhir:hapi-fhir-android:3.0.0-SNAPSHOT:dstu3@jar'`) and a number of dependencies have been cleaned up. This new version should actualy cut down the size of your final APK because it will no longer include the HAPI server stuff.

**Comment by MarcABernard** [comment]
Thanks for the quick reply!

That worked, but I also needed to add these:

compile 'ca.uhn.hapi.fhir:hapi-fhir-base:3.0.0-SNAPSHOT@jar'
compile 'ca.uhn.hapi.fhir:hapi-fhir-utilities:3.0.0-SNAPSHOT@jar'

**Comment by regnatpopulus** [comment]
Hi. I seem to be getting the same error. The integration project works for Android API greater that 23, but when I test on lower end devices, particularly API 21, 22, 23 I get the error below. When I use 24 and 25, the error does not appear.

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: ca.uhn.fhir.android.test, PID: 10462
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: ca.uhn.fhir.context.-$$Lambda$ModelScanner$uSzLWSu2DEH0tpG0Dyb0S0HKZ1s
        at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:116)
        at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:69)
        at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:767)
        at ca.uhn.fhir.context.FhirContext.validateInitialized(FhirContext.java:880)
        at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:383)
        at ca.uhn.fhir.rest.client.impl.GenericClient$SearchInternal.setType(GenericClient.java:1871)
        at ca.uhn.fhir.rest.client.impl.GenericClient$SearchInternal.forResource(GenericClient.java:1820)
        at ca.uhn.fhir.android.test.PatientFhirHelper.getPatients(PatientFhirHelper.java:33)
        at ca.uhn.fhir.android.ListCitizensActivity$1.doInBackground(ListCitizensActivity.java:40)
        at ca.uhn.fhir.android.ListCitizensActivity$1.doInBackground(ListCitizensActivity.java:35)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by mmacagno** [comment]
@regnatpopulus I seem to have stumbled on something very similar.  #1661 
Did you find a solution?

**Comment by regnatpopulus** [comment]
I traced the issue to the following https://developer.android.com/studio/write/java8-support . There are some java8 language features not supported in Android API 24 and below. Currently we are now recommending the use of API 24 and above in our app.
