### ISSUE TITLE
Issue with Hapi object saving to fhirbase

### ISSUE THREAD

**Issue by nishasumesh** [jamesagnew/hapi-fhir#723]
I was trying to convert a string (Patient json payload) to Hapi Patient resource(DSTU2). But I am getting the below error. 

Payload :
-------------
{"resourceType":"Patient","id":"3441d951-8f67-4d80-a8e6-fa6238181bde","meta":{"versionId":"d8116db3-4b7b-4e2a-b0c8-6e178798fb2a","lastUpdated":"2017-06-10T08:53:37.587322+00:00"},"identifier":[{"type":{"coding":[{"id":"P_MRN","code":"MRN","display":"MRN"}]},"value":"1234567"},{"type":{"coding":[{"id":"P_PID","code":"PID","display":"PID"}]},"value":"f5c9ebe6-9087-4121-93b1-680604168946"},{"type":{"coding":[{"id":"P_IPN","code":"IPN","display":"IPN"}]},"value":"234567890"}],"active":true,"name":[{"use":"usual","given":["arun Kumar"]}],"telecom":[{"system":"phone","value":"234567","use":"mobile"},{"system":"email","value":"test@test.com","use":"home"}],"gender":"male","birthDate":"2017-04-19","deceasedBoolean":false,"address":[{"use":"home","line":["test"],"city":"test","state":"test","postalCode":"23456"}],"maritalStatus":{"coding":[{"system":"http://hl7.org/fhir/v3/MaritalStatus","code":"S","display":"Never Married"}],"text":"Getrouwd"},"managingOrganization":{"reference":"Organization/19c0e6c3-9001-4f22-beb2-1eccd07dd02f"}}

My code
------------

Patient app = (Patient) ctx.newJsonParser().parseResource(responsePayload)

Error:
--------

16:24:33.791 [main] DEBUG ca.uhn.fhir.context.ModelScanner - Scanning resource block class: ca.uhn.fhir.model.dstu2.composite.ElementDefinitionDt$Constraint
16:24:33.794 [main] DEBUG ca.uhn.fhir.context.ModelScanner - Scanning resource class: ca.uhn.fhir.model.dstu2.resource.Device
Exception in thread "main" java.lang.NoSuchMethodError: org.hl7.fhir.instance.model.api.IBaseResource.getStructureFhirVersionEnum()Lca/uhn/fhir/context/FhirVersionEnum;
	at ca.uhn.fhir.context.RuntimeResourceDefinition.<init>(RuntimeResourceDefinition.java:62)
	at ca.uhn.fhir.context.ModelScanner.scanResource(ModelScanner.java:384)
	at ca.uhn.fhir.context.ModelScanner.scan(ModelScanner.java:233)
	at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:167)
	at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:96)
	at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:627)
	at ca.uhn.fhir.context.FhirContext.validateInitialized(FhirContext.java:798)
	at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:343)
	at ca.uhn.fhir.parser.ParserState$PreResourceState.enteringNewElement(ParserState.java:2053)
	at ca.uhn.fhir.parser.ParserState.enteringNewElement(ParserState.java:139)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:226)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:210)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:641)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:689)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:699)
	at com.cm.flowsheet.iText.DischargeSummaryHelper.getPayloadDetails(DischargeSummaryHelper.java:136)
	at com.cm.flowsheet.iText.DischargeSummaryHelper.fetchPatientResource(DischargeSummaryHelper.java:85)
	at com.cm.flowsheet.iText.DischargeSummaryHelper.main(DischargeSummaryHelper.java:72)

POM
------
        <dependency>
            <groupId>me.fhir</groupId>
            <artifactId>fhir-dstu2</artifactId>
            <version>1.0.1.7108</version>
        </dependency>
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-structures-dstu2</artifactId>
			<version>2.1</version>
		</dependency>

I need the fhir-dstu2 for my fhirbase stuffs and hapi libraries for resource creation. But both are not working together. Could you please suggest me a solution

**Comment by jamesagnew** [comment]
These two libraries will not work together and probably never will. What is the "fhirbase stuff" you need in the me.fhir one?

**Comment by nishasumesh** [comment]
Thank you James for your quick response. I have my fhir payload parsers dependent on me.fhir.
I resolved the issue. Just changed the pom file added the below dependencies (based on some of your other posts) and it started working.

		 <dependency>
		        <groupId>ca.uhn.hapi.fhir</groupId>
		        <artifactId>hapi-fhir-structures-dstu</artifactId>
		        <version>0.9</version>
		    </dependency>
		    <dependency>
		        <groupId>ca.uhn.hapi.fhir</groupId>
		        <artifactId>hapi-fhir-structures-dstu2</artifactId>
		        <version>0.9</version>

I think it was a problem with my below dependency
		<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-structures-dstu2</artifactId>
			<version>2.1</version>
		</dependency>

Everything is working fine now. Thank you...

**Comment by jamesagnew** [comment]
If you have it working, great- but I would recommend clearing out your dependencies on the parsers in the other library (or dropping your dependency on HAPI FHIR). You are using a version of HAPI that is over 2 years old, and you won't be able to upgrade using this strategy.
