### ISSUE TITLE
HAPI FHIR JPA Server .............................. FAILURE.  happens when FHIR/pom.xml is installed again.

### ISSUE THREAD

**Issue by SriLalithaV** [jamesagnew/hapi-fhir#75]
##  T E S T S

Running ca.uhn.fhir.jpa.dao.FhirResourceDaoTest
Tests run: 45, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.17 sec - in ca.uhn.fhir.jpa.dao.FhirResourceDaoTest
Running ca.uhn.fhir.jpa.dao.FhirSystemDaoTest
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.935 sec <<< FAILURE! - in ca.uhn.fhir.jpa.dao.FhirSystemDaoTest
testHistory(ca.uhn.fhir.jpa.dao.FhirSystemDaoTest)  Time elapsed: 0.093 sec  <<< FAILURE!
java.lang.AssertionError: expected:<Patient/91/_history/4> but was:<Patient/91/_history/3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at ca.uhn.fhir.jpa.dao.FhirSystemDaoTest.testHistory(FhirSystemDaoTest.java:76)

Results :

Failed tests: 
  FhirSystemDaoTest.testHistory:76 expected:<Patient/91/_history/4> but was:<Patient/91/_history/3>

Tests run: 53, Failures: 1, Errors: 0, Skipped: 0

**Comment by SriLalithaV** [comment]
Thanks James,
I am using the latest version HAPI 0.8 .  Java 7, OS – Windows.  May be, it is platform independent. ?

I tried MVN Clean.   It is working fine now.

Regards,
Lalitha.
