### ISSUE TITLE
Update from phloc-schematron to ph-schematron

### ISSUE THREAD

**Issue by phax** [jamesagnew/hapi-fhir#775]
As phloc-schematron is no longer maintained you may consider switching to ph-schematron instead.
https://github.com/phax/ph-schematron/ - still Apache 2, but Java 8. Last release is 4.3.4.
Drop me a note if you need help.

**Comment by Kaninsokk** [comment]
I second this, would be nice to use the updated version of phloc. When I validate with the old it looks for a zip I cannot find but it there in phax's.

**Comment by phax** [comment]
I maintained phloc-schematron, left company phloc, nobody needed it there so I forked it to ph-schematron. There it is maintained....

**Comment by jamesagnew** [comment]
We haven't yet brought HAPI up to Java 8 which is the only thing holding me back from this.

It's probably time though. I'm thinknig we will upgrade after the March release and make this change at that time.

**Comment by Kaninsokk** [comment]
Hi James,

What's the status on this? :)

**Comment by jamesagnew** [comment]
Hi @phax - I have this mostly working, although the OSGi tests only pass if I disable Schematron. I don't know enough about OSGi to be sure, but I'm guessing that Phloc-Schematron included the appropriate META-INF entries to be used as a bundle by Karaf while Ph-Schematron does not?

@johnpoth - Does this make sense?

You can see the failure in question by changing the value of [this constant](https://github.com/jamesagnew/hapi-fhir/blob/cf001142f71babb8ae080bf7248da3385f7b7831/osgi/hapi-fhir-karaf-integration-tests/src/test/java/ca/uhn/fhir/tests/integration/karaf/ValidationConstants.java)

This is the stack trace it fails with:

```
java.lang.ClassNotFoundException: com.helger.schematron.ISchematronResource not found by ca.uhn.hapi.fhir.hapi-fhir-base [12]

	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ca.uhn.fhir.tests.integration.karaf.dstu3.ResourceValidatorDstu3FeatureTest.testValidateResourceWithResourceElements(ResourceValidatorDstu3FeatureTest.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:68)
	at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
	at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ops4j.pax.exam.rbc.internal.RemoteBundleContextImpl.remoteCall(RemoteBundleContextImpl.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:835)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by phax** [comment]
@jamesagnew I'm also not an OSGI expert, but the export bundle management using the felix-bundle-plugin is still contained (and maintained). Do you eventually need to add different import packages (com.helger instead of com.phloc)???? Or is it, that bases classes (as in com.helger.commons from ph-commons project) are missing? Please ensure to remove all "phloc-" stuff and use the respective "ph-" stuff instead. hth

**Comment by jamesagnew** [comment]
@johnpoth - So, as far as I can tell I've done all that. I assume I missed something, but I've replaced all of the phloc dependencies with ph-schematron ones in the pom, and updated the features.xml as well.

The features.xml has been updated to have the following:

```xml
	<feature name='hapi-fhir-ph-schematron' version='${project.version}' start-level='50'>
		<bundle dependency='true'>
			mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.saxon/${servicemix_saxon_version}
		</bundle>
		<bundle dependency='true'>
			mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xmlresolver/${servicemix_xmlresolver_version}
		</bundle>
		<bundle dependency='true'>mvn:com.google.code.findbugs/jsr305/${jsr305_version}</bundle>
		<bundle dependency='true'>mvn:com.helger/ph-schematron/${ph_schematron_version}</bundle>
		<bundle dependency='true'>mvn:com.helger/ph-commons/${ph_commons_version}</bundle>
	</feature>
```

I note that I had to add `dependency=true` to the ph bundle entries in order for the validation step to pass. That wasn't there for the old phloc version.

**Comment by jamesagnew** [comment]
BTW if you want to have a look, it's all in the branch `775-replace-phloc-schematron`

**Comment by johnpoth** [comment]
@jamesagnew will take a look!

**Comment by johnpoth** [comment]
@jamesagnew @phax 

We will need https://github.com/phax/ph-commons/pull/10 and https://github.com/phax/ph-schematron/pull/68 to make this work. I've pushed the changes in https://github.com/johnpoth/hapi-fhir/tree/775-replace-phloc-schematron ( I didn't have the rights to push on the original branch) with the Karaf integration tests passing.

What would be cool is to have a ph-shematron Karaf feature that we would import in HAPI-FHIR and not have to specify all the dependencies. HTH

**Comment by phax** [comment]
Point taken. I just used it incorrectly.
Question: how did you identify to add `; resolution:=optional` ???
Shall I add it in all cases? (I have a tool to create this)

**Comment by johnpoth** [comment]
@phax great project! I added the `; resolution:=optional` for the SPIs for which I didn't see any implementation present in the ph-* codebase, so I figured they were optional? I'm afraid I don't have enough architectural knowledge to know which SPI implementations are needed for the bundle to be usable or not. Thanks!

**Comment by phax** [comment]
@johnpoth Thanks. Can you test with the latest SNAPSHOT versions or do you need releases of ph-commons and üh-schematron?

**Comment by johnpoth** [comment]
@phax sure I can test SNAPSHOT, are they available or should I build from source?

**Comment by phax** [comment]
They are on the Maven Central SNAPSHOT repo:
https://oss.sonatype.org/content/repositories/snapshots/com/helger/ph-commons/9.1.0-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/com/helger/ph-schematron/5.0.3-SNAPSHOT/
etc.

**Comment by johnpoth** [comment]
@phax just tested our karaf integration tests using the branch https://github.com/johnpoth/hapi-fhir/tree/775-replace-phloc-schematron using the updated SNAPSHOTs and all tests pass. Thanks!

**Comment by phax** [comment]
@johnpoth Thanks a lot for testing - I will create the respective releases asap. I will keep you posted here.

**Comment by jamesagnew** [comment]
Hmm, I have bumped the dependencies on the `775-replace-phloc-schematron` branch to the new release versions of ph-commons and ph-schematron but somehow this still isn't working for me.

At least locally it's giving me an error on the Karaf tests claiming `com.helger.schematron.ISchematronResource not found by ca.uhn.hapi.fhir.hapi-fhir-base [12]`

**Comment by johnpoth** [comment]
@phax  @jamesagnew  I get the same error. Reverting to 9.1.0-SNAPSHOT works.

**Comment by johnpoth** [comment]
Hi @phax, I've noticed you made [IURLProtocolRegistrarSPI](https://github.com/phax/ph-commons/commit/34ba0cdd019f9e3be39cc2a2ff19ac7b76136998) mandatory in ph-commons. Could you please tell us who provides this? Thanks!

**Comment by phax** [comment]
@johnpoth It's an optional SPI to provide additional URL protocols. In your setup, nobody implements this. But an SPI without an implementation should not be a problem, right?

**Comment by johnpoth** [comment]
@phax it's not a problem if marked as optional. It was set as mandatory in this [commit](https://github.com/phax/ph-commons/commit/34ba0cdd019f9e3be39cc2a2ff19ac7b76136998). See ph-commons/pom.xml diff where the `; resolution:=optional` was removed.

**Comment by phax** [comment]
@johnpoth Okay, so all must be optional in my case. Next release needed. Sorry. Will ping you when done

**Comment by johnpoth** [comment]
@phax no worries :) OSGI can be a bit of a pain! 

I've created an IRC channel #hapi-fhir on [freenode](https://webchat.freenode.net/) @jamesagnew

**Comment by phax** [comment]
@johnpoth please try with ph-commons 9.1.1-SNAPSHOT and ph-schematron 5.0.4-SNAPSHOT - if it works, I will release these versions "as-is". Thx

**Comment by jamesagnew** [comment]
Running a build now.

**Comment by johnpoth** [comment]
@phax @jamesagnew tests run fine for me. Thanks!

**Comment by jamesagnew** [comment]
Same. @phax I'll merge this as soon as these are released. Awesome!

**Comment by phax** [comment]
Both releases are now on Maven Central. Hopefully this can be closed now :)

**Comment by jamesagnew** [comment]
Annnnnd merged.

Thanks @phax and @johnpoth for all the help!
