### ISSUE TITLE
error during upload of r4 conformance resources (using hapi-fhir-cli)

### ISSUE THREAD

**Issue by jschneid-nmdp** [jamesagnew/hapi-fhir#820]
Error during upload of r4 conformance resources (using hapi-fhir-cli):

"Resource type is unknown or not supported on this server - http\://build.fhir.org/valueset-request-intent.html"

Stack trace:

```
./hapi-fhir-cli upload-definitions -f r4 -t http\://localhost:8080/baseR4
...
11:37:34 INFO  c.u.fhir.cli.ValidationDataUploader - Uploading profiles-resources StructureDefinition 35/166 : StructureDefinition/DeviceRequest
11:37:34 ERROR ca.uhn.fhir.cli.App - Error during execution: 
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 Bad Request: Invalid resource reference found at path[StructureDefinition.snapshot.element.binding.valueSet] - Resource type is unknown or not supported on this server - http\://build.fhir.org/valueset-request-intent.html
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:301)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:323)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:448)
	at ca.uhn.fhir.rest.client.impl.GenericClient$UpdateInternal.execute(GenericClient.java:2096)
	at ca.uhn.fhir.rest.client.impl.GenericClient$UpdateInternal.execute(GenericClient.java:2042)
	at ca.uhn.fhir.cli.ValidationDataUploader.uploadR4Profiles(ValidationDataUploader.java:522)
	at ca.uhn.fhir.cli.ValidationDataUploader.uploadDefinitionsR4(ValidationDataUploader.java:421)
	at ca.uhn.fhir.cli.ValidationDataUploader.run(ValidationDataUploader.java:140)
	at ca.uhn.fhir.cli.App.main(App.java:189)
```

**Comment by patrick-werner** [comment]
was fixed by:
07290ae8a0181c4c9d0ba863cf72f447065e66a1
