### ISSUE TITLE
v3.3.0 hapi-fhir-cli fatal error when uploading r4 conformance resources

### ISSUE THREAD

**Issue by jschneid-nmdp** [jamesagnew/hapi-fhir#940]
Using hapi-fhir-cli from the v3.3.0 release ...

```
wget https://github.com/jamesagnew/hapi-fhir/releases/download/v3.3.0/hapi-fhir-3.3.0-cli.zip
unzip hapi-fhir-3.3.0-cli.zip
```

Running hapi-fhir-cli to upload r4 conformance resources to a localhost:8080 server ...

```
./hapi-fhir-cli upload-definitions -f r4 -t http://localhost:8080/r4
```

The upload terminates abnormally, with a fatal error (HTTP 500) on ValueSet 76/1039: CodeSystem/consent-policy ...

```
11:55:47 INFO  c.u.fhir.cli.ValidationDataUploader - Uploading ValueSet 76/1039 : CodeSystem/consent-policy (19754 bytes}
11:55:47 ERROR ca.uhn.fhir.cli.App - Error during execution: 
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 Server Error: Failed to call access method
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:301)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:323)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:430)
	at ca.uhn.fhir.rest.client.impl.GenericClient$UpdateInternal.execute(GenericClient.java:2078)
	at ca.uhn.fhir.rest.client.impl.GenericClient$UpdateInternal.execute(GenericClient.java:2024)
	at ca.uhn.fhir.cli.ValidationDataUploader.uploadDefinitionsR4(ValidationDataUploader.java:372)
	at ca.uhn.fhir.cli.ValidationDataUploader.run(ValidationDataUploader.java:141)
	at ca.uhn.fhir.cli.App.main(App.java:189)
```

**Comment by anthonys123** [comment]
Related to issue #920.
