### ISSUE TITLE
NullPointerException in RuntimeChildChoiceDefinition

### ISSUE THREAD

**Issue by LarsGramMathiasen** [jamesagnew/hapi-fhir#944]
See fork https://github.com/LarsGramMathiasen/hapi-fhir for a test which reproduces the NPE.

`/hapi-fhir/tests/hapi-fhir-test-nullpointerexception$ mvn -DtrimStackTrace=false install`

The test creates a STU3 `FhirContext` and calls `encodeResourceToString()` on its `XmlParser` with a `Bundle` containing a profiled `EpisodeOfCare`. The EpisodeOfCare contains two nested components `_MyReferrerComponent` and `_OtherReferrerComponent` which seems to trigger the NPE. The input map `theClassToElementDefinitions` in the `sealAndInitialize()` method in  `RuntimeChildChoiceDefinition` does not contain the `IBase` class in the static list `myChoiceTypes` which seems to be unexpected. This happens for both above components.
Note that the NPE only happens once, per component, so in a production environment, a work-around is to call `encodeResourceToString()` 2-4 times (depending on the number of components which result in a NPE) for each application server, every time the application servers are restarted.

Stacktrace:
```
java.lang.NullPointerException
        at ca.uhn.fhir.context.RuntimeChildChoiceDefinition.sealAndInitialize(RuntimeChildChoiceDefinition.java:154)
        at ca.uhn.fhir.context.RuntimeChildDeclaredExtensionDefinition.sealAndInitialize(RuntimeChildDeclaredExtensionDefinition.java:208)
        at ca.uhn.fhir.context.BaseRuntimeElementDefinition.sealAndInitialize(BaseRuntimeElementDefinition.java:178)
        at ca.uhn.fhir.context.BaseRuntimeElementCompositeDefinition.sealAndInitialize(BaseRuntimeElementCompositeDefinition.java:466)
        at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:163)
        at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:67)
        at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:652)
        at ca.uhn.fhir.context.FhirContext.scanDatatype(FhirContext.java:631)
        at ca.uhn.fhir.context.FhirContext.getElementDefinition(FhirContext.java:235)
        at ca.uhn.fhir.context.RuntimeChildDeclaredExtensionDefinition.sealAndInitialize(RuntimeChildDeclaredExtensionDefinition.java:183)
        at ca.uhn.fhir.context.BaseRuntimeElementDefinition.sealAndInitialize(BaseRuntimeElementDefinition.java:178)
        at ca.uhn.fhir.context.BaseRuntimeElementCompositeDefinition.sealAndInitialize(BaseRuntimeElementCompositeDefinition.java:466)
        at ca.uhn.fhir.context.BaseRuntimeElementCompositeDefinition.validateSealed(BaseRuntimeElementCompositeDefinition.java:537)
        at ca.uhn.fhir.context.BaseRuntimeElementDefinition.getExtensions(BaseRuntimeElementDefinition.java:120)
        at ca.uhn.fhir.context.RuntimeChildDeclaredExtensionDefinition.sealAndInitialize(RuntimeChildDeclaredExtensionDefinition.java:200)
        at ca.uhn.fhir.context.BaseRuntimeElementDefinition.sealAndInitialize(BaseRuntimeElementDefinition.java:178)
        at ca.uhn.fhir.context.BaseRuntimeElementCompositeDefinition.sealAndInitialize(BaseRuntimeElementCompositeDefinition.java:466)
        at ca.uhn.fhir.context.RuntimeResourceDefinition.sealAndInitialize(RuntimeResourceDefinition.java:175)
        at ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:163)
        at ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:67)
        at ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:652)
        at ca.uhn.fhir.context.FhirContext.scanResourceType(FhirContext.java:638)
        at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:313)
        at ca.uhn.fhir.context.RuntimeChildDirectResource.getChildElementDefinitionByDatatype(RuntimeChildDirectResource.java:51)
        at ca.uhn.fhir.util.FhirTerser.visit(FhirTerser.java:586)
        at ca.uhn.fhir.util.FhirTerser.visit(FhirTerser.java:596)
        at ca.uhn.fhir.util.FhirTerser.getAllPopulatedChildElementsOfType(FhirTerser.java:129)
        at ca.uhn.fhir.parser.BaseParser.containResourcesForEncoding(BaseParser.java:200)
        at ca.uhn.fhir.parser.BaseParser.containResourcesForEncoding(BaseParser.java:240)
        at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:463)
        at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:458)
        at ca.uhn.fhir.parser.XmlParser.doEncodeResourceToWriter(XmlParser.java:109)
        at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:318)
        at ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:301)
        at ca.uhn.fhir.NullPointerExceptionTest.testNullPointerException(NullPointerExceptionTest.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

**Comment by JacobBangSSE** [comment]
We got the same problem at multiple places in our code base. It is kinda strange that the problem goes away after 3-4 attempts as described in the issue.

I can see this issue has not seen any update for some time. Has you (@LarsGramMathiasen) found any solution for this problem?
