### ISSUE TITLE
[###pls support to solve the issue Caused by: ca.uhn.fhir.parser.DataFormatException]

### ISSUE THREAD

**Issue by systemcia** [jamesagnew/hapi-fhir#952]
**dears:
    recently i have tried to use fhir to make my own Custom Structures contains the resource, the datatype and the provider,i have tested that it's ok to construct the xml , but i occur the issue when i tried to save the xml to the database:**
ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing UNKNOWN to URL UNKNOWN - ca.uhn.fhir.parser.DataFormatException: television has type ca.uhn.fhir.spring.boot.autoconfigure.entity.CustomDatatype but this is not a valid type for this element - Expected one of: [class org.hl7.fhir.dstu3.model.BooleanType, class org.hl7.fhir.dstu3.model.Quantity, class org.hl7.fhir.dstu3.model.Age, class org.hl7.fhir.dstu3.model.Annotation, class org.hl7.fhir.dstu3.model.Dosage, class org.hl7.fhir.dstu3.model.Signature, class org.hl7.fhir.dstu3.model.DateType, class org.hl7.fhir.dstu3.model.Extension, class org.hl7.fhir.dstu3.model.Identifier, class org.hl7.fhir.dstu3.model.ContactDetail, class org.hl7.fhir.dstu3.model.CodeableConcept, class org.hl7.fhir.dstu3.model.Reference, class org.hl7.fhir.dstu3.model.UriType, class org.hl7.fhir.dstu3.model.Duration, class org.hl7.fhir.utilities.xhtml.XhtmlNode, class org.hl7.fhir.dstu3.model.UsageContext, class org.hl7.fhir.dstu3.model.Coding, class org.hl7.fhir.dstu3.model.DataRequirement, class org.hl7.fhir.dstu3.model.HumanName, class org.hl7.fhir.dstu3.model.Distance, class org.hl7.fhir.dstu3.model.SimpleQuantity, class org.hl7.fhir.dstu3.model.ElementDefinition, class org.hl7.fhir.dstu3.model.Attachment, class org.hl7.fhir.dstu3.model.TriggerDefinition, class org.hl7.fhir.dstu3.model.IdType, class org.hl7.fhir.dstu3.model.Range, class org.hl7.fhir.dstu3.model.Address, class org.hl7.fhir.dstu3.model.Narrative, class org.hl7.fhir.dstu3.model.Contributor, class org.hl7.fhir.dstu3.model.Period, class org.hl7.fhir.dstu3.model.CodeType, class org.hl7.fhir.dstu3.model.Meta, class org.hl7.fhir.dstu3.model.Timing, class org.hl7.fhir.dstu3.model.StringType, class org.hl7.fhir.dstu3.model.RelatedArtifact, class org.hl7.fhir.dstu3.model.PositiveIntType, class org.hl7.fhir.dstu3.model.UnsignedIntType, class org.hl7.fhir.dstu3.model.ParameterDefinition, class org.hl7.fhir.dstu3.model.SampledData, class org.hl7.fhir.dstu3.model.MarkdownType, class org.hl7.fhir.dstu3.model.DecimalType, class org.hl7.fhir.dstu3.model.Base64BinaryType, class org.hl7.fhir.dstu3.model.TimeType, class org.hl7.fhir.dstu3.model.InstantType, class org.hl7.fhir.dstu3.model.Ratio, class org.hl7.fhir.dstu3.model.OidType, class org.hl7.fhir.dstu3.model.Count, class org.hl7.fhir.dstu3.model.DateTimeType, class org.hl7.fhir.dstu3.model.Money, class org.hl7.fhir.dstu3.model.ContactPoint, class org.hl7.fhir.dstu3.model.IntegerType]
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:365) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:430) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:564) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:519) ~[hapi-fhir-client-3.3.0.jar:na]
	at com.fiberhome.ms.fhir.ui.FhirTestReasource.v3mock(FhirTestReasource.java:249) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294) ~[resteasy-jaxrs-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248) ~[resteasy-jaxrs-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235) ~[resteasy-jaxrs-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.createModelAndView(ResteasyHandlerAdapter.java:96) [resteasy-spring-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:82) [resteasy-spring-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:26) [resteasy-spring-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.springmvc.ResteasyWebHandlerTemplate.handle(ResteasyWebHandlerTemplate.java:39) [resteasy-spring-3.1.3.Final.jar:3.1.3.Final]
	at org.jboss.resteasy.springmvc.ResteasyHandlerAdapter.handle(ResteasyHandlerAdapter.java:47) [resteasy-spring-3.1.3.Final.jar:3.1.3.Final]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) [spring-webmvc-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) [spring-webmvc-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870) [spring-webmvc-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855) [spring-webmvc-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) [spring-boot-actuator-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at com.fiberhome.smartms.web.support.filter.SsoFilter.doFilterInternal(SsoFilter.java:35) [smartms-spring-boot-starter-web-support-1.4.0-RELEASE.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167) [spring-session-1.3.1.RELEASE.jar:na]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80) [spring-session-1.3.1.RELEASE.jar:na]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-1.4.21.Final.jar:1.4.21.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: ca.uhn.fhir.parser.DataFormatException: television has type ca.uhn.fhir.spring.boot.autoconfigure.entity.CustomDatatype but this is not a valid type for this element - Expected one of: [class org.hl7.fhir.dstu3.model.BooleanType, class org.hl7.fhir.dstu3.model.Quantity, class org.hl7.fhir.dstu3.model.Age, class org.hl7.fhir.dstu3.model.Annotation, class org.hl7.fhir.dstu3.model.Dosage, class org.hl7.fhir.dstu3.model.Signature, class org.hl7.fhir.dstu3.model.DateType, class org.hl7.fhir.dstu3.model.Extension, class org.hl7.fhir.dstu3.model.Identifier, class org.hl7.fhir.dstu3.model.ContactDetail, class org.hl7.fhir.dstu3.model.CodeableConcept, class org.hl7.fhir.dstu3.model.Reference, class org.hl7.fhir.dstu3.model.UriType, class org.hl7.fhir.dstu3.model.Duration, class org.hl7.fhir.utilities.xhtml.XhtmlNode, class org.hl7.fhir.dstu3.model.UsageContext, class org.hl7.fhir.dstu3.model.Coding, class org.hl7.fhir.dstu3.model.DataRequirement, class org.hl7.fhir.dstu3.model.HumanName, class org.hl7.fhir.dstu3.model.Distance, class org.hl7.fhir.dstu3.model.SimpleQuantity, class org.hl7.fhir.dstu3.model.ElementDefinition, class org.hl7.fhir.dstu3.model.Attachment, class org.hl7.fhir.dstu3.model.TriggerDefinition, class org.hl7.fhir.dstu3.model.IdType, class org.hl7.fhir.dstu3.model.Range, class org.hl7.fhir.dstu3.model.Address, class org.hl7.fhir.dstu3.model.Narrative, class org.hl7.fhir.dstu3.model.Contributor, class org.hl7.fhir.dstu3.model.Period, class org.hl7.fhir.dstu3.model.CodeType, class org.hl7.fhir.dstu3.model.Meta, class org.hl7.fhir.dstu3.model.Timing, class org.hl7.fhir.dstu3.model.StringType, class org.hl7.fhir.dstu3.model.RelatedArtifact, class org.hl7.fhir.dstu3.model.PositiveIntType, class org.hl7.fhir.dstu3.model.UnsignedIntType, class org.hl7.fhir.dstu3.model.ParameterDefinition, class org.hl7.fhir.dstu3.model.SampledData, class org.hl7.fhir.dstu3.model.MarkdownType, class org.hl7.fhir.dstu3.model.DecimalType, class org.hl7.fhir.dstu3.model.Base64BinaryType, class org.hl7.fhir.dstu3.model.TimeType, class org.hl7.fhir.dstu3.model.InstantType, class org.hl7.fhir.dstu3.model.Ratio, class org.hl7.fhir.dstu3.model.OidType, class org.hl7.fhir.dstu3.model.Count, class org.hl7.fhir.dstu3.model.DateTimeType, class org.hl7.fhir.dstu3.model.Money, class org.hl7.fhir.dstu3.model.ContactPoint, class org.hl7.fhir.dstu3.model.IntegerType]
	at ca.uhn.fhir.parser.BaseParser.throwExceptionForUnknownChildType(BaseParser.java:916) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.BaseParser.getChildNameAndDef(BaseParser.java:367) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.XmlParser.encodeCompositeElementToStreamWriter(XmlParser.java:376) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:485) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.XmlParser.encodeResourceToXmlStreamWriter(XmlParser.java:458) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.XmlParser.doEncodeResourceToWriter(XmlParser.java:109) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:307) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:290) ~[hapi-fhir-base-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.method.BaseHttpClientInvocationWithContents.encodeContents(BaseHttpClientInvocationWithContents.java:205) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.method.BaseHttpClientInvocationWithContents.asHttpRequest(BaseHttpClientInvocationWithContents.java:155) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.method.HttpPostClientInvocation.asHttpRequest(HttpPostClientInvocation.java:32) ~[hapi-fhir-client-3.3.0.jar:na]
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:247) ~[hapi-fhir-client-3.3.0.jar:na]
	... 90 common frames omitted

**i have tried to register my own resource and datatype in the initialize function , but it's not ok.**
`@Override
		protected void initialize() throws ServletException {
			super.initialize();
			this.fhirContext.registerCustomType(CustomResource.class);
			this.fhirContext.registerCustomType(CustomDatatype.class);
			this.fhirContext.registerCustomType(CustomDatatype2.class);
			setFhirContext(this.fhirContext);
			this.resourceProviders.add(new MyProvider());
			setResourceProviders(this.resourceProviders);
			setPagingProvider(this.pagingProvider);
			setInterceptors(this.interceptors);

			setServerAddressStrategy(new HardcodedServerAddressStrategy(this.properties.getServer().getPath()));

			customize();
		}`
**pls give me a support for how to save and recognize my custom datatype, thank you very much!**

**Comment by jamesagnew** [comment]
Hi @systemcia . Please see our FAQ for information on where to ask for help with HAPI FHIR:

http://hapifhir.io/hapi-fhir-faq.html
