### ISSUE TITLE
PATCH by Id gives HTTP 404

### ISSUE THREAD

**Issue by johnpoth** [jamesagnew/hapi-fhir#955]
When trying to execute PATCH request by id:
`
String patch = "[ { \"op\":\"replace\", \"path\":\"/active\", \"value\":true } ]";
client.patch().withBody(patch).withId(sId).execute();
`

The JPA server responds with 404 because it looks like it's [trying](https://github.com/jamesagnew/hapi-fhir/blob/833cfd6988138f484a7788470d43dd49b714adba/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/RestfulServer.java#L273) to lookup the resource type using the id.

Trying to use a conditionalByUrl:

`client.patch().withBody(thePatchBody).conditionalByUrl(theSearchUrl).execute();`

Gives a "Failed to call access method" error:
`Caused by: ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 Server Error: Failed to call access method
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:301)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:323)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:430)
        at ca.uhn.fhir.rest.client.impl.GenericClient$PatchInternal.execute(GenericClient.java:1407)
        at ca.uhn.fhir.rest.client.impl.GenericClient$PatchInternal.execute(GenericClient.java:1348)
`
Thanks!

**Comment by jamesagnew** [comment]
Fixing this as a part of #1850
