### ISSUE TITLE
ExceptionInInitializerError on some Androids on FHirContext.forR4()

### ISSUE THREAD

**Issue by brianreinhold** [jamesagnew/hapi-fhir#962]
This issue seems related to issue #722. However, the suggestions given there no longer apply and the gradle file already has these dependencies

    implementation 'org.slf4j:slf4j-android:1.7.25@jar'
    implementation 'ca.uhn.hapi.fhir:hapi-fhir-structures-r4:3.1.0'

This error is not appearing when I run the same code on newer Androids. I have limited devices, but the error is occurring on a 4.0.4 OS version on a Samsung S. The error states "Could not find method org.slf4j.LoggerFactory.getLogger, referenced from method ca.uhn.fhir.context.FhirContext"

The full logcat trace is
`05-25 04:52:39.789 2718-2718/com.lampreynetworks.ahd.oilbath2 I/dalvikvm: Could not find method org.slf4j.LoggerFactory.getLogger, referenced from method ca.uhn.fhir.context.FhirContext.<clinit>
05-25 04:52:39.792 2718-2718/com.lampreynetworks.ahd.oilbath2 W/dalvikvm: VFY: unable to resolve static method 64980: Lorg/slf4j/LoggerFactory;.getLogger (Ljava/lang/Class;)Lorg/slf4j/Logger;
05-25 04:52:39.792 2718-2718/com.lampreynetworks.ahd.oilbath2 D/dalvikvm: VFY: replacing opcode 0x71 at 0x0008
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 I/dalvikvm: Could not find method org.slf4j.Logger.info, referenced from method ca.uhn.fhir.context.FhirContext.<init>
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 W/dalvikvm: VFY: unable to resolve interface method 64962: Lorg/slf4j/Logger;.info (Ljava/lang/String;Ljava/lang/Object;)V
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 D/dalvikvm: VFY: replacing opcode 0x72 at 0x00ba
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 I/dalvikvm: Could not find method org.slf4j.Logger.info, referenced from method ca.uhn.fhir.context.FhirContext.<init>
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 W/dalvikvm: VFY: unable to resolve interface method 64962: Lorg/slf4j/Logger;.info (Ljava/lang/String;Ljava/lang/Object;)V
05-25 04:52:39.800 2718-2718/com.lampreynetworks.ahd.oilbath2 D/dalvikvm: VFY: replacing opcode 0x72 at 0x00cc
05-25 04:52:39.820 2718-2718/com.lampreynetworks.ahd.oilbath2 W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lca/uhn/fhir/context/FhirContext;
05-25 04:52:39.820 2718-2718/com.lampreynetworks.ahd.oilbath2 D/AndroidRuntime: Shutting down VM
05-25 04:52:39.820 2718-2718/com.lampreynetworks.ahd.oilbath2 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40a671f8)
05-25 04:52:39.832 2718-2718/com.lampreynetworks.ahd.oilbath2 E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at com.lampreynetworks.ahd.pcd.fhir.FHIRBundles.<init>(FHIRBundles.java:51)
        at com.lampreynetworks.ahd.oilbath.BluetoothPanService.<init>(BluetoothPanService.java:97)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2234)`

**Comment by brianreinhold** [comment]
Don't use this version anymore so I cannot make any further comments anyways!
