### ISSUE TITLE
Performance in JPA reads

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#963]
I have noticed when returning large pages of search results we spend a lot of time in stack traces such as the trace below.

From this I am guessing that if we're loading 20 resources for the page, we're doing 20 DB operations individually to fetch them. This could definitely be streamlined.

I do also believe if the resources have tags this further slows things down quite a bit so I'm betting that the tag loading is a subsequent DB operation as well.

My general theory is that to load a set of resources we should be able to do one DB query for the resource bodies, and one more DB query for all of their tags/profiles/security labels.

```
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener
.java:85)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1397)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1463)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.ja
va:206)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy197.findForIdAndVersion(Unknown Source)
        at ca.uhn.fhir.jpa.dao.BaseHapiFhirDao.toResource(BaseHapiFhirDao.java:1570)
        at com.sun.proxy.$Proxy215.toResource(Unknown Source)
        at ca.uhn.fhir.jpa.dao.SearchBuilder.doLoadPids(SearchBuilder.java:1608)
        at ca.uhn.fhir.jpa.dao.SearchBuilder.loadResourcesByPid(SearchBuilder.java:1667)
        at ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider.toResourceList(PersistedJpaBundleProvider.java:281)
        at ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider$1.doInTransaction(PersistedJpaBundleProvider.java:141)
        at ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider$1.doInTransaction(PersistedJpaBundleProvider.java:138)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider.doSearchOrEverything(PersistedJpaBundleProvider.java:138)
        at ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider.getResources(PersistedJpaBundleProvider.java:214)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.createBundleFromBundleProvider(BaseResourceReturningMethodBinding.java:156)
        at ca.uhn.fhir.rest.server.method.PageMethodBinding.handlePagingRequest(PageMethodBinding.java:129)
```

**Comment by anthonys123** [comment]
James - I'd be happy to help with this one.  Let me know if I should work it.

**Comment by frankjtao** [comment]
Is the relationship between HFJ_RESOURCE and HFJ_RES_VER one to one by RES_ID and VER_ID?

**Comment by frankjtao** [comment]
Fixed the looping issue for the HFJ_RES_VER (ResourceHistoryTable). Will look for tag loading.
